// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=19.761000,HLS_SYN_LAT=479500,HLS_SYN_TPT=none,HLS_SYN_MEM=32,HLS_SYN_DSP=14,HLS_SYN_FF=9872,HLS_SYN_LUT=20207,HLS_VERSION=2019_2}" *)

module top (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_data_address0,
        input_data_ce0,
        input_data_q0,
        input_data_address1,
        input_data_ce1,
        input_data_q1,
        output_data_address0,
        output_data_ce0,
        output_data_we0,
        output_data_d0,
        output_data_address1,
        output_data_ce1,
        output_data_we1,
        output_data_d1
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] input_data_address0;
output   input_data_ce0;
input  [31:0] input_data_q0;
output  [13:0] input_data_address1;
output   input_data_ce1;
input  [31:0] input_data_q1;
output  [11:0] output_data_address0;
output   output_data_ce0;
output   output_data_we0;
output  [31:0] output_data_d0;
output  [11:0] output_data_address1;
output   output_data_ce1;
output   output_data_we1;
output  [31:0] output_data_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [9:0] Q_0_address0;
reg    Q_0_ce0;
reg    Q_0_we0;
wire   [31:0] Q_0_q0;
reg   [9:0] Q_0_address1;
reg    Q_0_ce1;
reg    Q_0_we1;
wire   [31:0] Q_0_q1;
reg   [9:0] Q_1_address0;
reg    Q_1_ce0;
reg    Q_1_we0;
wire   [31:0] Q_1_q0;
reg   [9:0] Q_1_address1;
reg    Q_1_ce1;
reg    Q_1_we1;
wire   [31:0] Q_1_q1;
reg   [9:0] Q_2_address0;
reg    Q_2_ce0;
reg    Q_2_we0;
wire   [31:0] Q_2_q0;
reg   [9:0] Q_2_address1;
reg    Q_2_ce1;
reg    Q_2_we1;
wire   [31:0] Q_2_q1;
reg   [9:0] Q_3_address0;
reg    Q_3_ce0;
reg    Q_3_we0;
wire   [31:0] Q_3_q0;
reg   [9:0] Q_3_address1;
reg    Q_3_ce1;
reg    Q_3_we1;
wire   [31:0] Q_3_q1;
reg   [9:0] K_0_address0;
reg    K_0_ce0;
reg    K_0_we0;
wire   [31:0] K_0_q0;
reg   [9:0] K_0_address1;
reg    K_0_ce1;
reg    K_0_we1;
wire   [31:0] K_0_q1;
reg   [9:0] K_1_address0;
reg    K_1_ce0;
reg    K_1_we0;
wire   [31:0] K_1_q0;
reg   [9:0] K_1_address1;
reg    K_1_ce1;
reg    K_1_we1;
wire   [31:0] K_1_q1;
reg   [9:0] K_2_address0;
reg    K_2_ce0;
reg    K_2_we0;
wire   [31:0] K_2_q0;
reg   [9:0] K_2_address1;
reg    K_2_ce1;
reg    K_2_we1;
wire   [31:0] K_2_q1;
reg   [9:0] K_3_address0;
reg    K_3_ce0;
reg    K_3_we0;
wire   [31:0] K_3_q0;
reg   [9:0] K_3_address1;
reg    K_3_ce1;
reg    K_3_we1;
wire   [31:0] K_3_q1;
reg   [9:0] V_0_address0;
reg    V_0_ce0;
reg    V_0_we0;
wire   [31:0] V_0_q0;
reg    V_0_ce1;
reg    V_0_we1;
reg   [9:0] V_1_address0;
reg    V_1_ce0;
reg    V_1_we0;
wire   [31:0] V_1_q0;
reg    V_1_ce1;
reg    V_1_we1;
reg   [9:0] V_2_address0;
reg    V_2_ce0;
reg    V_2_we0;
wire   [31:0] V_2_q0;
reg    V_2_ce1;
reg    V_2_we1;
reg   [9:0] V_3_address0;
reg    V_3_ce0;
reg    V_3_we0;
wire   [31:0] V_3_q0;
reg    V_3_ce1;
reg    V_3_we1;
reg   [9:0] OUT_0_address0;
reg    OUT_0_ce0;
reg    OUT_0_we0;
wire   [31:0] OUT_0_q0;
reg    OUT_0_ce1;
wire   [31:0] OUT_0_q1;
reg   [9:0] OUT_1_address0;
reg    OUT_1_ce0;
reg    OUT_1_we0;
wire   [31:0] OUT_1_q0;
reg    OUT_1_ce1;
wire   [31:0] OUT_1_q1;
reg   [9:0] OUT_2_address0;
reg    OUT_2_ce0;
reg    OUT_2_we0;
wire   [31:0] OUT_2_q0;
reg    OUT_2_ce1;
wire   [31:0] OUT_2_q1;
reg   [9:0] OUT_3_address0;
reg    OUT_3_ce0;
reg    OUT_3_we0;
wire   [31:0] OUT_3_q0;
reg    OUT_3_ce1;
wire   [31:0] OUT_3_q1;
wire    grp_compute_attention_fu_56_ap_start;
wire    grp_compute_attention_fu_56_ap_done;
wire    grp_compute_attention_fu_56_ap_idle;
wire    grp_compute_attention_fu_56_ap_ready;
wire   [9:0] grp_compute_attention_fu_56_Q_0_address0;
wire    grp_compute_attention_fu_56_Q_0_ce0;
wire   [9:0] grp_compute_attention_fu_56_Q_0_address1;
wire    grp_compute_attention_fu_56_Q_0_ce1;
wire   [9:0] grp_compute_attention_fu_56_Q_1_address0;
wire    grp_compute_attention_fu_56_Q_1_ce0;
wire   [9:0] grp_compute_attention_fu_56_Q_1_address1;
wire    grp_compute_attention_fu_56_Q_1_ce1;
wire   [9:0] grp_compute_attention_fu_56_Q_2_address0;
wire    grp_compute_attention_fu_56_Q_2_ce0;
wire   [9:0] grp_compute_attention_fu_56_Q_2_address1;
wire    grp_compute_attention_fu_56_Q_2_ce1;
wire   [9:0] grp_compute_attention_fu_56_Q_3_address0;
wire    grp_compute_attention_fu_56_Q_3_ce0;
wire   [9:0] grp_compute_attention_fu_56_Q_3_address1;
wire    grp_compute_attention_fu_56_Q_3_ce1;
wire   [9:0] grp_compute_attention_fu_56_K_0_address0;
wire    grp_compute_attention_fu_56_K_0_ce0;
wire   [9:0] grp_compute_attention_fu_56_K_0_address1;
wire    grp_compute_attention_fu_56_K_0_ce1;
wire   [9:0] grp_compute_attention_fu_56_K_1_address0;
wire    grp_compute_attention_fu_56_K_1_ce0;
wire   [9:0] grp_compute_attention_fu_56_K_1_address1;
wire    grp_compute_attention_fu_56_K_1_ce1;
wire   [9:0] grp_compute_attention_fu_56_K_2_address0;
wire    grp_compute_attention_fu_56_K_2_ce0;
wire   [9:0] grp_compute_attention_fu_56_K_2_address1;
wire    grp_compute_attention_fu_56_K_2_ce1;
wire   [9:0] grp_compute_attention_fu_56_K_3_address0;
wire    grp_compute_attention_fu_56_K_3_ce0;
wire   [9:0] grp_compute_attention_fu_56_K_3_address1;
wire    grp_compute_attention_fu_56_K_3_ce1;
wire   [9:0] grp_compute_attention_fu_56_V_0_address0;
wire    grp_compute_attention_fu_56_V_0_ce0;
wire   [9:0] grp_compute_attention_fu_56_V_1_address0;
wire    grp_compute_attention_fu_56_V_1_ce0;
wire   [9:0] grp_compute_attention_fu_56_V_2_address0;
wire    grp_compute_attention_fu_56_V_2_ce0;
wire   [9:0] grp_compute_attention_fu_56_V_3_address0;
wire    grp_compute_attention_fu_56_V_3_ce0;
wire   [9:0] grp_compute_attention_fu_56_OUT_0_address0;
wire    grp_compute_attention_fu_56_OUT_0_ce0;
wire    grp_compute_attention_fu_56_OUT_0_we0;
wire   [31:0] grp_compute_attention_fu_56_OUT_0_d0;
wire   [9:0] grp_compute_attention_fu_56_OUT_1_address0;
wire    grp_compute_attention_fu_56_OUT_1_ce0;
wire    grp_compute_attention_fu_56_OUT_1_we0;
wire   [31:0] grp_compute_attention_fu_56_OUT_1_d0;
wire   [9:0] grp_compute_attention_fu_56_OUT_2_address0;
wire    grp_compute_attention_fu_56_OUT_2_ce0;
wire    grp_compute_attention_fu_56_OUT_2_we0;
wire   [31:0] grp_compute_attention_fu_56_OUT_2_d0;
wire   [9:0] grp_compute_attention_fu_56_OUT_3_address0;
wire    grp_compute_attention_fu_56_OUT_3_ce0;
wire    grp_compute_attention_fu_56_OUT_3_we0;
wire   [31:0] grp_compute_attention_fu_56_OUT_3_d0;
wire    grp_load_and_rearrange_q_fu_92_ap_start;
wire    grp_load_and_rearrange_q_fu_92_ap_done;
wire    grp_load_and_rearrange_q_fu_92_ap_idle;
wire    grp_load_and_rearrange_q_fu_92_ap_ready;
wire   [13:0] grp_load_and_rearrange_q_fu_92_input_data_address0;
wire    grp_load_and_rearrange_q_fu_92_input_data_ce0;
wire   [13:0] grp_load_and_rearrange_q_fu_92_input_data_address1;
wire    grp_load_and_rearrange_q_fu_92_input_data_ce1;
wire   [9:0] grp_load_and_rearrange_q_fu_92_Q_0_address0;
wire    grp_load_and_rearrange_q_fu_92_Q_0_ce0;
wire    grp_load_and_rearrange_q_fu_92_Q_0_we0;
wire   [31:0] grp_load_and_rearrange_q_fu_92_Q_0_d0;
wire   [9:0] grp_load_and_rearrange_q_fu_92_Q_0_address1;
wire    grp_load_and_rearrange_q_fu_92_Q_0_ce1;
wire    grp_load_and_rearrange_q_fu_92_Q_0_we1;
wire   [31:0] grp_load_and_rearrange_q_fu_92_Q_0_d1;
wire   [9:0] grp_load_and_rearrange_q_fu_92_Q_1_address0;
wire    grp_load_and_rearrange_q_fu_92_Q_1_ce0;
wire    grp_load_and_rearrange_q_fu_92_Q_1_we0;
wire   [31:0] grp_load_and_rearrange_q_fu_92_Q_1_d0;
wire   [9:0] grp_load_and_rearrange_q_fu_92_Q_1_address1;
wire    grp_load_and_rearrange_q_fu_92_Q_1_ce1;
wire    grp_load_and_rearrange_q_fu_92_Q_1_we1;
wire   [31:0] grp_load_and_rearrange_q_fu_92_Q_1_d1;
wire   [9:0] grp_load_and_rearrange_q_fu_92_Q_2_address0;
wire    grp_load_and_rearrange_q_fu_92_Q_2_ce0;
wire    grp_load_and_rearrange_q_fu_92_Q_2_we0;
wire   [31:0] grp_load_and_rearrange_q_fu_92_Q_2_d0;
wire   [9:0] grp_load_and_rearrange_q_fu_92_Q_2_address1;
wire    grp_load_and_rearrange_q_fu_92_Q_2_ce1;
wire    grp_load_and_rearrange_q_fu_92_Q_2_we1;
wire   [31:0] grp_load_and_rearrange_q_fu_92_Q_2_d1;
wire   [9:0] grp_load_and_rearrange_q_fu_92_Q_3_address0;
wire    grp_load_and_rearrange_q_fu_92_Q_3_ce0;
wire    grp_load_and_rearrange_q_fu_92_Q_3_we0;
wire   [31:0] grp_load_and_rearrange_q_fu_92_Q_3_d0;
wire   [9:0] grp_load_and_rearrange_q_fu_92_Q_3_address1;
wire    grp_load_and_rearrange_q_fu_92_Q_3_ce1;
wire    grp_load_and_rearrange_q_fu_92_Q_3_we1;
wire   [31:0] grp_load_and_rearrange_q_fu_92_Q_3_d1;
wire   [9:0] grp_load_and_rearrange_q_fu_92_K_0_address0;
wire    grp_load_and_rearrange_q_fu_92_K_0_ce0;
wire    grp_load_and_rearrange_q_fu_92_K_0_we0;
wire   [31:0] grp_load_and_rearrange_q_fu_92_K_0_d0;
wire   [9:0] grp_load_and_rearrange_q_fu_92_K_0_address1;
wire    grp_load_and_rearrange_q_fu_92_K_0_ce1;
wire    grp_load_and_rearrange_q_fu_92_K_0_we1;
wire   [31:0] grp_load_and_rearrange_q_fu_92_K_0_d1;
wire   [9:0] grp_load_and_rearrange_q_fu_92_K_1_address0;
wire    grp_load_and_rearrange_q_fu_92_K_1_ce0;
wire    grp_load_and_rearrange_q_fu_92_K_1_we0;
wire   [31:0] grp_load_and_rearrange_q_fu_92_K_1_d0;
wire   [9:0] grp_load_and_rearrange_q_fu_92_K_1_address1;
wire    grp_load_and_rearrange_q_fu_92_K_1_ce1;
wire    grp_load_and_rearrange_q_fu_92_K_1_we1;
wire   [31:0] grp_load_and_rearrange_q_fu_92_K_1_d1;
wire   [9:0] grp_load_and_rearrange_q_fu_92_K_2_address0;
wire    grp_load_and_rearrange_q_fu_92_K_2_ce0;
wire    grp_load_and_rearrange_q_fu_92_K_2_we0;
wire   [31:0] grp_load_and_rearrange_q_fu_92_K_2_d0;
wire   [9:0] grp_load_and_rearrange_q_fu_92_K_2_address1;
wire    grp_load_and_rearrange_q_fu_92_K_2_ce1;
wire    grp_load_and_rearrange_q_fu_92_K_2_we1;
wire   [31:0] grp_load_and_rearrange_q_fu_92_K_2_d1;
wire   [9:0] grp_load_and_rearrange_q_fu_92_K_3_address0;
wire    grp_load_and_rearrange_q_fu_92_K_3_ce0;
wire    grp_load_and_rearrange_q_fu_92_K_3_we0;
wire   [31:0] grp_load_and_rearrange_q_fu_92_K_3_d0;
wire   [9:0] grp_load_and_rearrange_q_fu_92_K_3_address1;
wire    grp_load_and_rearrange_q_fu_92_K_3_ce1;
wire    grp_load_and_rearrange_q_fu_92_K_3_we1;
wire   [31:0] grp_load_and_rearrange_q_fu_92_K_3_d1;
wire   [9:0] grp_load_and_rearrange_q_fu_92_V_0_address0;
wire    grp_load_and_rearrange_q_fu_92_V_0_ce0;
wire    grp_load_and_rearrange_q_fu_92_V_0_we0;
wire   [31:0] grp_load_and_rearrange_q_fu_92_V_0_d0;
wire   [9:0] grp_load_and_rearrange_q_fu_92_V_0_address1;
wire    grp_load_and_rearrange_q_fu_92_V_0_ce1;
wire    grp_load_and_rearrange_q_fu_92_V_0_we1;
wire   [31:0] grp_load_and_rearrange_q_fu_92_V_0_d1;
wire   [9:0] grp_load_and_rearrange_q_fu_92_V_1_address0;
wire    grp_load_and_rearrange_q_fu_92_V_1_ce0;
wire    grp_load_and_rearrange_q_fu_92_V_1_we0;
wire   [31:0] grp_load_and_rearrange_q_fu_92_V_1_d0;
wire   [9:0] grp_load_and_rearrange_q_fu_92_V_1_address1;
wire    grp_load_and_rearrange_q_fu_92_V_1_ce1;
wire    grp_load_and_rearrange_q_fu_92_V_1_we1;
wire   [31:0] grp_load_and_rearrange_q_fu_92_V_1_d1;
wire   [9:0] grp_load_and_rearrange_q_fu_92_V_2_address0;
wire    grp_load_and_rearrange_q_fu_92_V_2_ce0;
wire    grp_load_and_rearrange_q_fu_92_V_2_we0;
wire   [31:0] grp_load_and_rearrange_q_fu_92_V_2_d0;
wire   [9:0] grp_load_and_rearrange_q_fu_92_V_2_address1;
wire    grp_load_and_rearrange_q_fu_92_V_2_ce1;
wire    grp_load_and_rearrange_q_fu_92_V_2_we1;
wire   [31:0] grp_load_and_rearrange_q_fu_92_V_2_d1;
wire   [9:0] grp_load_and_rearrange_q_fu_92_V_3_address0;
wire    grp_load_and_rearrange_q_fu_92_V_3_ce0;
wire    grp_load_and_rearrange_q_fu_92_V_3_we0;
wire   [31:0] grp_load_and_rearrange_q_fu_92_V_3_d0;
wire   [9:0] grp_load_and_rearrange_q_fu_92_V_3_address1;
wire    grp_load_and_rearrange_q_fu_92_V_3_ce1;
wire    grp_load_and_rearrange_q_fu_92_V_3_we1;
wire   [31:0] grp_load_and_rearrange_q_fu_92_V_3_d1;
wire    grp_store_output_fu_122_ap_start;
wire    grp_store_output_fu_122_ap_done;
wire    grp_store_output_fu_122_ap_idle;
wire    grp_store_output_fu_122_ap_ready;
wire   [11:0] grp_store_output_fu_122_output_data_address0;
wire    grp_store_output_fu_122_output_data_ce0;
wire    grp_store_output_fu_122_output_data_we0;
wire   [31:0] grp_store_output_fu_122_output_data_d0;
wire   [11:0] grp_store_output_fu_122_output_data_address1;
wire    grp_store_output_fu_122_output_data_ce1;
wire    grp_store_output_fu_122_output_data_we1;
wire   [31:0] grp_store_output_fu_122_output_data_d1;
wire   [9:0] grp_store_output_fu_122_OUT_0_address0;
wire    grp_store_output_fu_122_OUT_0_ce0;
wire   [9:0] grp_store_output_fu_122_OUT_0_address1;
wire    grp_store_output_fu_122_OUT_0_ce1;
wire   [9:0] grp_store_output_fu_122_OUT_1_address0;
wire    grp_store_output_fu_122_OUT_1_ce0;
wire   [9:0] grp_store_output_fu_122_OUT_1_address1;
wire    grp_store_output_fu_122_OUT_1_ce1;
wire   [9:0] grp_store_output_fu_122_OUT_2_address0;
wire    grp_store_output_fu_122_OUT_2_ce0;
wire   [9:0] grp_store_output_fu_122_OUT_2_address1;
wire    grp_store_output_fu_122_OUT_2_ce1;
wire   [9:0] grp_store_output_fu_122_OUT_3_address0;
wire    grp_store_output_fu_122_OUT_3_ce0;
wire   [9:0] grp_store_output_fu_122_OUT_3_address1;
wire    grp_store_output_fu_122_OUT_3_ce1;
reg    grp_compute_attention_fu_56_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_load_and_rearrange_q_fu_92_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_store_output_fu_122_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [5:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_compute_attention_fu_56_ap_start_reg = 1'b0;
#0 grp_load_and_rearrange_q_fu_92_ap_start_reg = 1'b0;
#0 grp_store_output_fu_122_ap_start_reg = 1'b0;
end

top_Q_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
Q_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Q_0_address0),
    .ce0(Q_0_ce0),
    .we0(Q_0_we0),
    .d0(grp_load_and_rearrange_q_fu_92_Q_0_d0),
    .q0(Q_0_q0),
    .address1(Q_0_address1),
    .ce1(Q_0_ce1),
    .we1(Q_0_we1),
    .d1(grp_load_and_rearrange_q_fu_92_Q_0_d1),
    .q1(Q_0_q1)
);

top_Q_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
Q_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Q_1_address0),
    .ce0(Q_1_ce0),
    .we0(Q_1_we0),
    .d0(grp_load_and_rearrange_q_fu_92_Q_1_d0),
    .q0(Q_1_q0),
    .address1(Q_1_address1),
    .ce1(Q_1_ce1),
    .we1(Q_1_we1),
    .d1(grp_load_and_rearrange_q_fu_92_Q_1_d1),
    .q1(Q_1_q1)
);

top_Q_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
Q_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Q_2_address0),
    .ce0(Q_2_ce0),
    .we0(Q_2_we0),
    .d0(grp_load_and_rearrange_q_fu_92_Q_2_d0),
    .q0(Q_2_q0),
    .address1(Q_2_address1),
    .ce1(Q_2_ce1),
    .we1(Q_2_we1),
    .d1(grp_load_and_rearrange_q_fu_92_Q_2_d1),
    .q1(Q_2_q1)
);

top_Q_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
Q_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(Q_3_address0),
    .ce0(Q_3_ce0),
    .we0(Q_3_we0),
    .d0(grp_load_and_rearrange_q_fu_92_Q_3_d0),
    .q0(Q_3_q0),
    .address1(Q_3_address1),
    .ce1(Q_3_ce1),
    .we1(Q_3_we1),
    .d1(grp_load_and_rearrange_q_fu_92_Q_3_d1),
    .q1(Q_3_q1)
);

top_Q_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
K_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(K_0_address0),
    .ce0(K_0_ce0),
    .we0(K_0_we0),
    .d0(grp_load_and_rearrange_q_fu_92_K_0_d0),
    .q0(K_0_q0),
    .address1(K_0_address1),
    .ce1(K_0_ce1),
    .we1(K_0_we1),
    .d1(grp_load_and_rearrange_q_fu_92_K_0_d1),
    .q1(K_0_q1)
);

top_Q_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
K_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(K_1_address0),
    .ce0(K_1_ce0),
    .we0(K_1_we0),
    .d0(grp_load_and_rearrange_q_fu_92_K_1_d0),
    .q0(K_1_q0),
    .address1(K_1_address1),
    .ce1(K_1_ce1),
    .we1(K_1_we1),
    .d1(grp_load_and_rearrange_q_fu_92_K_1_d1),
    .q1(K_1_q1)
);

top_Q_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
K_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(K_2_address0),
    .ce0(K_2_ce0),
    .we0(K_2_we0),
    .d0(grp_load_and_rearrange_q_fu_92_K_2_d0),
    .q0(K_2_q0),
    .address1(K_2_address1),
    .ce1(K_2_ce1),
    .we1(K_2_we1),
    .d1(grp_load_and_rearrange_q_fu_92_K_2_d1),
    .q1(K_2_q1)
);

top_Q_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
K_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(K_3_address0),
    .ce0(K_3_ce0),
    .we0(K_3_we0),
    .d0(grp_load_and_rearrange_q_fu_92_K_3_d0),
    .q0(K_3_q0),
    .address1(K_3_address1),
    .ce1(K_3_ce1),
    .we1(K_3_we1),
    .d1(grp_load_and_rearrange_q_fu_92_K_3_d1),
    .q1(K_3_q1)
);

top_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
V_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(V_0_address0),
    .ce0(V_0_ce0),
    .we0(V_0_we0),
    .d0(grp_load_and_rearrange_q_fu_92_V_0_d0),
    .q0(V_0_q0),
    .address1(grp_load_and_rearrange_q_fu_92_V_0_address1),
    .ce1(V_0_ce1),
    .we1(V_0_we1),
    .d1(grp_load_and_rearrange_q_fu_92_V_0_d1)
);

top_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(V_1_address0),
    .ce0(V_1_ce0),
    .we0(V_1_we0),
    .d0(grp_load_and_rearrange_q_fu_92_V_1_d0),
    .q0(V_1_q0),
    .address1(grp_load_and_rearrange_q_fu_92_V_1_address1),
    .ce1(V_1_ce1),
    .we1(V_1_we1),
    .d1(grp_load_and_rearrange_q_fu_92_V_1_d1)
);

top_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(V_2_address0),
    .ce0(V_2_ce0),
    .we0(V_2_we0),
    .d0(grp_load_and_rearrange_q_fu_92_V_2_d0),
    .q0(V_2_q0),
    .address1(grp_load_and_rearrange_q_fu_92_V_2_address1),
    .ce1(V_2_ce1),
    .we1(V_2_we1),
    .d1(grp_load_and_rearrange_q_fu_92_V_2_d1)
);

top_V_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
V_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(V_3_address0),
    .ce0(V_3_ce0),
    .we0(V_3_we0),
    .d0(grp_load_and_rearrange_q_fu_92_V_3_d0),
    .q0(V_3_q0),
    .address1(grp_load_and_rearrange_q_fu_92_V_3_address1),
    .ce1(V_3_ce1),
    .we1(V_3_we1),
    .d1(grp_load_and_rearrange_q_fu_92_V_3_d1)
);

top_OUT_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
OUT_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(OUT_0_address0),
    .ce0(OUT_0_ce0),
    .we0(OUT_0_we0),
    .d0(grp_compute_attention_fu_56_OUT_0_d0),
    .q0(OUT_0_q0),
    .address1(grp_store_output_fu_122_OUT_0_address1),
    .ce1(OUT_0_ce1),
    .q1(OUT_0_q1)
);

top_OUT_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
OUT_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(OUT_1_address0),
    .ce0(OUT_1_ce0),
    .we0(OUT_1_we0),
    .d0(grp_compute_attention_fu_56_OUT_1_d0),
    .q0(OUT_1_q0),
    .address1(grp_store_output_fu_122_OUT_1_address1),
    .ce1(OUT_1_ce1),
    .q1(OUT_1_q1)
);

top_OUT_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
OUT_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(OUT_2_address0),
    .ce0(OUT_2_ce0),
    .we0(OUT_2_we0),
    .d0(grp_compute_attention_fu_56_OUT_2_d0),
    .q0(OUT_2_q0),
    .address1(grp_store_output_fu_122_OUT_2_address1),
    .ce1(OUT_2_ce1),
    .q1(OUT_2_q1)
);

top_OUT_0 #(
    .DataWidth( 32 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
OUT_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(OUT_3_address0),
    .ce0(OUT_3_ce0),
    .we0(OUT_3_we0),
    .d0(grp_compute_attention_fu_56_OUT_3_d0),
    .q0(OUT_3_q0),
    .address1(grp_store_output_fu_122_OUT_3_address1),
    .ce1(OUT_3_ce1),
    .q1(OUT_3_q1)
);

compute_attention grp_compute_attention_fu_56(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_attention_fu_56_ap_start),
    .ap_done(grp_compute_attention_fu_56_ap_done),
    .ap_idle(grp_compute_attention_fu_56_ap_idle),
    .ap_ready(grp_compute_attention_fu_56_ap_ready),
    .Q_0_address0(grp_compute_attention_fu_56_Q_0_address0),
    .Q_0_ce0(grp_compute_attention_fu_56_Q_0_ce0),
    .Q_0_q0(Q_0_q0),
    .Q_0_address1(grp_compute_attention_fu_56_Q_0_address1),
    .Q_0_ce1(grp_compute_attention_fu_56_Q_0_ce1),
    .Q_0_q1(Q_0_q1),
    .Q_1_address0(grp_compute_attention_fu_56_Q_1_address0),
    .Q_1_ce0(grp_compute_attention_fu_56_Q_1_ce0),
    .Q_1_q0(Q_1_q0),
    .Q_1_address1(grp_compute_attention_fu_56_Q_1_address1),
    .Q_1_ce1(grp_compute_attention_fu_56_Q_1_ce1),
    .Q_1_q1(Q_1_q1),
    .Q_2_address0(grp_compute_attention_fu_56_Q_2_address0),
    .Q_2_ce0(grp_compute_attention_fu_56_Q_2_ce0),
    .Q_2_q0(Q_2_q0),
    .Q_2_address1(grp_compute_attention_fu_56_Q_2_address1),
    .Q_2_ce1(grp_compute_attention_fu_56_Q_2_ce1),
    .Q_2_q1(Q_2_q1),
    .Q_3_address0(grp_compute_attention_fu_56_Q_3_address0),
    .Q_3_ce0(grp_compute_attention_fu_56_Q_3_ce0),
    .Q_3_q0(Q_3_q0),
    .Q_3_address1(grp_compute_attention_fu_56_Q_3_address1),
    .Q_3_ce1(grp_compute_attention_fu_56_Q_3_ce1),
    .Q_3_q1(Q_3_q1),
    .K_0_address0(grp_compute_attention_fu_56_K_0_address0),
    .K_0_ce0(grp_compute_attention_fu_56_K_0_ce0),
    .K_0_q0(K_0_q0),
    .K_0_address1(grp_compute_attention_fu_56_K_0_address1),
    .K_0_ce1(grp_compute_attention_fu_56_K_0_ce1),
    .K_0_q1(K_0_q1),
    .K_1_address0(grp_compute_attention_fu_56_K_1_address0),
    .K_1_ce0(grp_compute_attention_fu_56_K_1_ce0),
    .K_1_q0(K_1_q0),
    .K_1_address1(grp_compute_attention_fu_56_K_1_address1),
    .K_1_ce1(grp_compute_attention_fu_56_K_1_ce1),
    .K_1_q1(K_1_q1),
    .K_2_address0(grp_compute_attention_fu_56_K_2_address0),
    .K_2_ce0(grp_compute_attention_fu_56_K_2_ce0),
    .K_2_q0(K_2_q0),
    .K_2_address1(grp_compute_attention_fu_56_K_2_address1),
    .K_2_ce1(grp_compute_attention_fu_56_K_2_ce1),
    .K_2_q1(K_2_q1),
    .K_3_address0(grp_compute_attention_fu_56_K_3_address0),
    .K_3_ce0(grp_compute_attention_fu_56_K_3_ce0),
    .K_3_q0(K_3_q0),
    .K_3_address1(grp_compute_attention_fu_56_K_3_address1),
    .K_3_ce1(grp_compute_attention_fu_56_K_3_ce1),
    .K_3_q1(K_3_q1),
    .V_0_address0(grp_compute_attention_fu_56_V_0_address0),
    .V_0_ce0(grp_compute_attention_fu_56_V_0_ce0),
    .V_0_q0(V_0_q0),
    .V_1_address0(grp_compute_attention_fu_56_V_1_address0),
    .V_1_ce0(grp_compute_attention_fu_56_V_1_ce0),
    .V_1_q0(V_1_q0),
    .V_2_address0(grp_compute_attention_fu_56_V_2_address0),
    .V_2_ce0(grp_compute_attention_fu_56_V_2_ce0),
    .V_2_q0(V_2_q0),
    .V_3_address0(grp_compute_attention_fu_56_V_3_address0),
    .V_3_ce0(grp_compute_attention_fu_56_V_3_ce0),
    .V_3_q0(V_3_q0),
    .OUT_0_address0(grp_compute_attention_fu_56_OUT_0_address0),
    .OUT_0_ce0(grp_compute_attention_fu_56_OUT_0_ce0),
    .OUT_0_we0(grp_compute_attention_fu_56_OUT_0_we0),
    .OUT_0_d0(grp_compute_attention_fu_56_OUT_0_d0),
    .OUT_1_address0(grp_compute_attention_fu_56_OUT_1_address0),
    .OUT_1_ce0(grp_compute_attention_fu_56_OUT_1_ce0),
    .OUT_1_we0(grp_compute_attention_fu_56_OUT_1_we0),
    .OUT_1_d0(grp_compute_attention_fu_56_OUT_1_d0),
    .OUT_2_address0(grp_compute_attention_fu_56_OUT_2_address0),
    .OUT_2_ce0(grp_compute_attention_fu_56_OUT_2_ce0),
    .OUT_2_we0(grp_compute_attention_fu_56_OUT_2_we0),
    .OUT_2_d0(grp_compute_attention_fu_56_OUT_2_d0),
    .OUT_3_address0(grp_compute_attention_fu_56_OUT_3_address0),
    .OUT_3_ce0(grp_compute_attention_fu_56_OUT_3_ce0),
    .OUT_3_we0(grp_compute_attention_fu_56_OUT_3_we0),
    .OUT_3_d0(grp_compute_attention_fu_56_OUT_3_d0)
);

load_and_rearrange_q grp_load_and_rearrange_q_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_load_and_rearrange_q_fu_92_ap_start),
    .ap_done(grp_load_and_rearrange_q_fu_92_ap_done),
    .ap_idle(grp_load_and_rearrange_q_fu_92_ap_idle),
    .ap_ready(grp_load_and_rearrange_q_fu_92_ap_ready),
    .input_data_address0(grp_load_and_rearrange_q_fu_92_input_data_address0),
    .input_data_ce0(grp_load_and_rearrange_q_fu_92_input_data_ce0),
    .input_data_q0(input_data_q0),
    .input_data_address1(grp_load_and_rearrange_q_fu_92_input_data_address1),
    .input_data_ce1(grp_load_and_rearrange_q_fu_92_input_data_ce1),
    .input_data_q1(input_data_q1),
    .Q_0_address0(grp_load_and_rearrange_q_fu_92_Q_0_address0),
    .Q_0_ce0(grp_load_and_rearrange_q_fu_92_Q_0_ce0),
    .Q_0_we0(grp_load_and_rearrange_q_fu_92_Q_0_we0),
    .Q_0_d0(grp_load_and_rearrange_q_fu_92_Q_0_d0),
    .Q_0_address1(grp_load_and_rearrange_q_fu_92_Q_0_address1),
    .Q_0_ce1(grp_load_and_rearrange_q_fu_92_Q_0_ce1),
    .Q_0_we1(grp_load_and_rearrange_q_fu_92_Q_0_we1),
    .Q_0_d1(grp_load_and_rearrange_q_fu_92_Q_0_d1),
    .Q_1_address0(grp_load_and_rearrange_q_fu_92_Q_1_address0),
    .Q_1_ce0(grp_load_and_rearrange_q_fu_92_Q_1_ce0),
    .Q_1_we0(grp_load_and_rearrange_q_fu_92_Q_1_we0),
    .Q_1_d0(grp_load_and_rearrange_q_fu_92_Q_1_d0),
    .Q_1_address1(grp_load_and_rearrange_q_fu_92_Q_1_address1),
    .Q_1_ce1(grp_load_and_rearrange_q_fu_92_Q_1_ce1),
    .Q_1_we1(grp_load_and_rearrange_q_fu_92_Q_1_we1),
    .Q_1_d1(grp_load_and_rearrange_q_fu_92_Q_1_d1),
    .Q_2_address0(grp_load_and_rearrange_q_fu_92_Q_2_address0),
    .Q_2_ce0(grp_load_and_rearrange_q_fu_92_Q_2_ce0),
    .Q_2_we0(grp_load_and_rearrange_q_fu_92_Q_2_we0),
    .Q_2_d0(grp_load_and_rearrange_q_fu_92_Q_2_d0),
    .Q_2_address1(grp_load_and_rearrange_q_fu_92_Q_2_address1),
    .Q_2_ce1(grp_load_and_rearrange_q_fu_92_Q_2_ce1),
    .Q_2_we1(grp_load_and_rearrange_q_fu_92_Q_2_we1),
    .Q_2_d1(grp_load_and_rearrange_q_fu_92_Q_2_d1),
    .Q_3_address0(grp_load_and_rearrange_q_fu_92_Q_3_address0),
    .Q_3_ce0(grp_load_and_rearrange_q_fu_92_Q_3_ce0),
    .Q_3_we0(grp_load_and_rearrange_q_fu_92_Q_3_we0),
    .Q_3_d0(grp_load_and_rearrange_q_fu_92_Q_3_d0),
    .Q_3_address1(grp_load_and_rearrange_q_fu_92_Q_3_address1),
    .Q_3_ce1(grp_load_and_rearrange_q_fu_92_Q_3_ce1),
    .Q_3_we1(grp_load_and_rearrange_q_fu_92_Q_3_we1),
    .Q_3_d1(grp_load_and_rearrange_q_fu_92_Q_3_d1),
    .K_0_address0(grp_load_and_rearrange_q_fu_92_K_0_address0),
    .K_0_ce0(grp_load_and_rearrange_q_fu_92_K_0_ce0),
    .K_0_we0(grp_load_and_rearrange_q_fu_92_K_0_we0),
    .K_0_d0(grp_load_and_rearrange_q_fu_92_K_0_d0),
    .K_0_address1(grp_load_and_rearrange_q_fu_92_K_0_address1),
    .K_0_ce1(grp_load_and_rearrange_q_fu_92_K_0_ce1),
    .K_0_we1(grp_load_and_rearrange_q_fu_92_K_0_we1),
    .K_0_d1(grp_load_and_rearrange_q_fu_92_K_0_d1),
    .K_1_address0(grp_load_and_rearrange_q_fu_92_K_1_address0),
    .K_1_ce0(grp_load_and_rearrange_q_fu_92_K_1_ce0),
    .K_1_we0(grp_load_and_rearrange_q_fu_92_K_1_we0),
    .K_1_d0(grp_load_and_rearrange_q_fu_92_K_1_d0),
    .K_1_address1(grp_load_and_rearrange_q_fu_92_K_1_address1),
    .K_1_ce1(grp_load_and_rearrange_q_fu_92_K_1_ce1),
    .K_1_we1(grp_load_and_rearrange_q_fu_92_K_1_we1),
    .K_1_d1(grp_load_and_rearrange_q_fu_92_K_1_d1),
    .K_2_address0(grp_load_and_rearrange_q_fu_92_K_2_address0),
    .K_2_ce0(grp_load_and_rearrange_q_fu_92_K_2_ce0),
    .K_2_we0(grp_load_and_rearrange_q_fu_92_K_2_we0),
    .K_2_d0(grp_load_and_rearrange_q_fu_92_K_2_d0),
    .K_2_address1(grp_load_and_rearrange_q_fu_92_K_2_address1),
    .K_2_ce1(grp_load_and_rearrange_q_fu_92_K_2_ce1),
    .K_2_we1(grp_load_and_rearrange_q_fu_92_K_2_we1),
    .K_2_d1(grp_load_and_rearrange_q_fu_92_K_2_d1),
    .K_3_address0(grp_load_and_rearrange_q_fu_92_K_3_address0),
    .K_3_ce0(grp_load_and_rearrange_q_fu_92_K_3_ce0),
    .K_3_we0(grp_load_and_rearrange_q_fu_92_K_3_we0),
    .K_3_d0(grp_load_and_rearrange_q_fu_92_K_3_d0),
    .K_3_address1(grp_load_and_rearrange_q_fu_92_K_3_address1),
    .K_3_ce1(grp_load_and_rearrange_q_fu_92_K_3_ce1),
    .K_3_we1(grp_load_and_rearrange_q_fu_92_K_3_we1),
    .K_3_d1(grp_load_and_rearrange_q_fu_92_K_3_d1),
    .V_0_address0(grp_load_and_rearrange_q_fu_92_V_0_address0),
    .V_0_ce0(grp_load_and_rearrange_q_fu_92_V_0_ce0),
    .V_0_we0(grp_load_and_rearrange_q_fu_92_V_0_we0),
    .V_0_d0(grp_load_and_rearrange_q_fu_92_V_0_d0),
    .V_0_address1(grp_load_and_rearrange_q_fu_92_V_0_address1),
    .V_0_ce1(grp_load_and_rearrange_q_fu_92_V_0_ce1),
    .V_0_we1(grp_load_and_rearrange_q_fu_92_V_0_we1),
    .V_0_d1(grp_load_and_rearrange_q_fu_92_V_0_d1),
    .V_1_address0(grp_load_and_rearrange_q_fu_92_V_1_address0),
    .V_1_ce0(grp_load_and_rearrange_q_fu_92_V_1_ce0),
    .V_1_we0(grp_load_and_rearrange_q_fu_92_V_1_we0),
    .V_1_d0(grp_load_and_rearrange_q_fu_92_V_1_d0),
    .V_1_address1(grp_load_and_rearrange_q_fu_92_V_1_address1),
    .V_1_ce1(grp_load_and_rearrange_q_fu_92_V_1_ce1),
    .V_1_we1(grp_load_and_rearrange_q_fu_92_V_1_we1),
    .V_1_d1(grp_load_and_rearrange_q_fu_92_V_1_d1),
    .V_2_address0(grp_load_and_rearrange_q_fu_92_V_2_address0),
    .V_2_ce0(grp_load_and_rearrange_q_fu_92_V_2_ce0),
    .V_2_we0(grp_load_and_rearrange_q_fu_92_V_2_we0),
    .V_2_d0(grp_load_and_rearrange_q_fu_92_V_2_d0),
    .V_2_address1(grp_load_and_rearrange_q_fu_92_V_2_address1),
    .V_2_ce1(grp_load_and_rearrange_q_fu_92_V_2_ce1),
    .V_2_we1(grp_load_and_rearrange_q_fu_92_V_2_we1),
    .V_2_d1(grp_load_and_rearrange_q_fu_92_V_2_d1),
    .V_3_address0(grp_load_and_rearrange_q_fu_92_V_3_address0),
    .V_3_ce0(grp_load_and_rearrange_q_fu_92_V_3_ce0),
    .V_3_we0(grp_load_and_rearrange_q_fu_92_V_3_we0),
    .V_3_d0(grp_load_and_rearrange_q_fu_92_V_3_d0),
    .V_3_address1(grp_load_and_rearrange_q_fu_92_V_3_address1),
    .V_3_ce1(grp_load_and_rearrange_q_fu_92_V_3_ce1),
    .V_3_we1(grp_load_and_rearrange_q_fu_92_V_3_we1),
    .V_3_d1(grp_load_and_rearrange_q_fu_92_V_3_d1)
);

store_output grp_store_output_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_store_output_fu_122_ap_start),
    .ap_done(grp_store_output_fu_122_ap_done),
    .ap_idle(grp_store_output_fu_122_ap_idle),
    .ap_ready(grp_store_output_fu_122_ap_ready),
    .output_data_address0(grp_store_output_fu_122_output_data_address0),
    .output_data_ce0(grp_store_output_fu_122_output_data_ce0),
    .output_data_we0(grp_store_output_fu_122_output_data_we0),
    .output_data_d0(grp_store_output_fu_122_output_data_d0),
    .output_data_address1(grp_store_output_fu_122_output_data_address1),
    .output_data_ce1(grp_store_output_fu_122_output_data_ce1),
    .output_data_we1(grp_store_output_fu_122_output_data_we1),
    .output_data_d1(grp_store_output_fu_122_output_data_d1),
    .OUT_0_address0(grp_store_output_fu_122_OUT_0_address0),
    .OUT_0_ce0(grp_store_output_fu_122_OUT_0_ce0),
    .OUT_0_q0(OUT_0_q0),
    .OUT_0_address1(grp_store_output_fu_122_OUT_0_address1),
    .OUT_0_ce1(grp_store_output_fu_122_OUT_0_ce1),
    .OUT_0_q1(OUT_0_q1),
    .OUT_1_address0(grp_store_output_fu_122_OUT_1_address0),
    .OUT_1_ce0(grp_store_output_fu_122_OUT_1_ce0),
    .OUT_1_q0(OUT_1_q0),
    .OUT_1_address1(grp_store_output_fu_122_OUT_1_address1),
    .OUT_1_ce1(grp_store_output_fu_122_OUT_1_ce1),
    .OUT_1_q1(OUT_1_q1),
    .OUT_2_address0(grp_store_output_fu_122_OUT_2_address0),
    .OUT_2_ce0(grp_store_output_fu_122_OUT_2_ce0),
    .OUT_2_q0(OUT_2_q0),
    .OUT_2_address1(grp_store_output_fu_122_OUT_2_address1),
    .OUT_2_ce1(grp_store_output_fu_122_OUT_2_ce1),
    .OUT_2_q1(OUT_2_q1),
    .OUT_3_address0(grp_store_output_fu_122_OUT_3_address0),
    .OUT_3_ce0(grp_store_output_fu_122_OUT_3_ce0),
    .OUT_3_q0(OUT_3_q0),
    .OUT_3_address1(grp_store_output_fu_122_OUT_3_address1),
    .OUT_3_ce1(grp_store_output_fu_122_OUT_3_ce1),
    .OUT_3_q1(OUT_3_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_attention_fu_56_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_compute_attention_fu_56_ap_start_reg <= 1'b1;
        end else if ((grp_compute_attention_fu_56_ap_ready == 1'b1)) begin
            grp_compute_attention_fu_56_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_load_and_rearrange_q_fu_92_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_load_and_rearrange_q_fu_92_ap_start_reg <= 1'b1;
        end else if ((grp_load_and_rearrange_q_fu_92_ap_ready == 1'b1)) begin
            grp_load_and_rearrange_q_fu_92_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_store_output_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_store_output_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_store_output_fu_122_ap_ready == 1'b1)) begin
            grp_store_output_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_0_address0 = grp_load_and_rearrange_q_fu_92_K_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_0_address0 = grp_compute_attention_fu_56_K_0_address0;
    end else begin
        K_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_0_address1 = grp_load_and_rearrange_q_fu_92_K_0_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_0_address1 = grp_compute_attention_fu_56_K_0_address1;
    end else begin
        K_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_0_ce0 = grp_load_and_rearrange_q_fu_92_K_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_0_ce0 = grp_compute_attention_fu_56_K_0_ce0;
    end else begin
        K_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_0_ce1 = grp_load_and_rearrange_q_fu_92_K_0_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_0_ce1 = grp_compute_attention_fu_56_K_0_ce1;
    end else begin
        K_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_0_we0 = grp_load_and_rearrange_q_fu_92_K_0_we0;
    end else begin
        K_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_0_we1 = grp_load_and_rearrange_q_fu_92_K_0_we1;
    end else begin
        K_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_1_address0 = grp_load_and_rearrange_q_fu_92_K_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_1_address0 = grp_compute_attention_fu_56_K_1_address0;
    end else begin
        K_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_1_address1 = grp_load_and_rearrange_q_fu_92_K_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_1_address1 = grp_compute_attention_fu_56_K_1_address1;
    end else begin
        K_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_1_ce0 = grp_load_and_rearrange_q_fu_92_K_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_1_ce0 = grp_compute_attention_fu_56_K_1_ce0;
    end else begin
        K_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_1_ce1 = grp_load_and_rearrange_q_fu_92_K_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_1_ce1 = grp_compute_attention_fu_56_K_1_ce1;
    end else begin
        K_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_1_we0 = grp_load_and_rearrange_q_fu_92_K_1_we0;
    end else begin
        K_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_1_we1 = grp_load_and_rearrange_q_fu_92_K_1_we1;
    end else begin
        K_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_2_address0 = grp_load_and_rearrange_q_fu_92_K_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_2_address0 = grp_compute_attention_fu_56_K_2_address0;
    end else begin
        K_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_2_address1 = grp_load_and_rearrange_q_fu_92_K_2_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_2_address1 = grp_compute_attention_fu_56_K_2_address1;
    end else begin
        K_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_2_ce0 = grp_load_and_rearrange_q_fu_92_K_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_2_ce0 = grp_compute_attention_fu_56_K_2_ce0;
    end else begin
        K_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_2_ce1 = grp_load_and_rearrange_q_fu_92_K_2_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_2_ce1 = grp_compute_attention_fu_56_K_2_ce1;
    end else begin
        K_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_2_we0 = grp_load_and_rearrange_q_fu_92_K_2_we0;
    end else begin
        K_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_2_we1 = grp_load_and_rearrange_q_fu_92_K_2_we1;
    end else begin
        K_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_3_address0 = grp_load_and_rearrange_q_fu_92_K_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_3_address0 = grp_compute_attention_fu_56_K_3_address0;
    end else begin
        K_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_3_address1 = grp_load_and_rearrange_q_fu_92_K_3_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_3_address1 = grp_compute_attention_fu_56_K_3_address1;
    end else begin
        K_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_3_ce0 = grp_load_and_rearrange_q_fu_92_K_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_3_ce0 = grp_compute_attention_fu_56_K_3_ce0;
    end else begin
        K_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_3_ce1 = grp_load_and_rearrange_q_fu_92_K_3_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        K_3_ce1 = grp_compute_attention_fu_56_K_3_ce1;
    end else begin
        K_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_3_we0 = grp_load_and_rearrange_q_fu_92_K_3_we0;
    end else begin
        K_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        K_3_we1 = grp_load_and_rearrange_q_fu_92_K_3_we1;
    end else begin
        K_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OUT_0_address0 = grp_store_output_fu_122_OUT_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OUT_0_address0 = grp_compute_attention_fu_56_OUT_0_address0;
    end else begin
        OUT_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OUT_0_ce0 = grp_store_output_fu_122_OUT_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OUT_0_ce0 = grp_compute_attention_fu_56_OUT_0_ce0;
    end else begin
        OUT_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OUT_0_ce1 = grp_store_output_fu_122_OUT_0_ce1;
    end else begin
        OUT_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OUT_0_we0 = grp_compute_attention_fu_56_OUT_0_we0;
    end else begin
        OUT_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OUT_1_address0 = grp_store_output_fu_122_OUT_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OUT_1_address0 = grp_compute_attention_fu_56_OUT_1_address0;
    end else begin
        OUT_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OUT_1_ce0 = grp_store_output_fu_122_OUT_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OUT_1_ce0 = grp_compute_attention_fu_56_OUT_1_ce0;
    end else begin
        OUT_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OUT_1_ce1 = grp_store_output_fu_122_OUT_1_ce1;
    end else begin
        OUT_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OUT_1_we0 = grp_compute_attention_fu_56_OUT_1_we0;
    end else begin
        OUT_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OUT_2_address0 = grp_store_output_fu_122_OUT_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OUT_2_address0 = grp_compute_attention_fu_56_OUT_2_address0;
    end else begin
        OUT_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OUT_2_ce0 = grp_store_output_fu_122_OUT_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OUT_2_ce0 = grp_compute_attention_fu_56_OUT_2_ce0;
    end else begin
        OUT_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OUT_2_ce1 = grp_store_output_fu_122_OUT_2_ce1;
    end else begin
        OUT_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OUT_2_we0 = grp_compute_attention_fu_56_OUT_2_we0;
    end else begin
        OUT_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OUT_3_address0 = grp_store_output_fu_122_OUT_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OUT_3_address0 = grp_compute_attention_fu_56_OUT_3_address0;
    end else begin
        OUT_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OUT_3_ce0 = grp_store_output_fu_122_OUT_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        OUT_3_ce0 = grp_compute_attention_fu_56_OUT_3_ce0;
    end else begin
        OUT_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        OUT_3_ce1 = grp_store_output_fu_122_OUT_3_ce1;
    end else begin
        OUT_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        OUT_3_we0 = grp_compute_attention_fu_56_OUT_3_we0;
    end else begin
        OUT_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_0_address0 = grp_load_and_rearrange_q_fu_92_Q_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_0_address0 = grp_compute_attention_fu_56_Q_0_address0;
    end else begin
        Q_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_0_address1 = grp_load_and_rearrange_q_fu_92_Q_0_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_0_address1 = grp_compute_attention_fu_56_Q_0_address1;
    end else begin
        Q_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_0_ce0 = grp_load_and_rearrange_q_fu_92_Q_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_0_ce0 = grp_compute_attention_fu_56_Q_0_ce0;
    end else begin
        Q_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_0_ce1 = grp_load_and_rearrange_q_fu_92_Q_0_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_0_ce1 = grp_compute_attention_fu_56_Q_0_ce1;
    end else begin
        Q_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_0_we0 = grp_load_and_rearrange_q_fu_92_Q_0_we0;
    end else begin
        Q_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_0_we1 = grp_load_and_rearrange_q_fu_92_Q_0_we1;
    end else begin
        Q_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_1_address0 = grp_load_and_rearrange_q_fu_92_Q_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_1_address0 = grp_compute_attention_fu_56_Q_1_address0;
    end else begin
        Q_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_1_address1 = grp_load_and_rearrange_q_fu_92_Q_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_1_address1 = grp_compute_attention_fu_56_Q_1_address1;
    end else begin
        Q_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_1_ce0 = grp_load_and_rearrange_q_fu_92_Q_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_1_ce0 = grp_compute_attention_fu_56_Q_1_ce0;
    end else begin
        Q_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_1_ce1 = grp_load_and_rearrange_q_fu_92_Q_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_1_ce1 = grp_compute_attention_fu_56_Q_1_ce1;
    end else begin
        Q_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_1_we0 = grp_load_and_rearrange_q_fu_92_Q_1_we0;
    end else begin
        Q_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_1_we1 = grp_load_and_rearrange_q_fu_92_Q_1_we1;
    end else begin
        Q_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_2_address0 = grp_load_and_rearrange_q_fu_92_Q_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_2_address0 = grp_compute_attention_fu_56_Q_2_address0;
    end else begin
        Q_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_2_address1 = grp_load_and_rearrange_q_fu_92_Q_2_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_2_address1 = grp_compute_attention_fu_56_Q_2_address1;
    end else begin
        Q_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_2_ce0 = grp_load_and_rearrange_q_fu_92_Q_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_2_ce0 = grp_compute_attention_fu_56_Q_2_ce0;
    end else begin
        Q_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_2_ce1 = grp_load_and_rearrange_q_fu_92_Q_2_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_2_ce1 = grp_compute_attention_fu_56_Q_2_ce1;
    end else begin
        Q_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_2_we0 = grp_load_and_rearrange_q_fu_92_Q_2_we0;
    end else begin
        Q_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_2_we1 = grp_load_and_rearrange_q_fu_92_Q_2_we1;
    end else begin
        Q_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_3_address0 = grp_load_and_rearrange_q_fu_92_Q_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_3_address0 = grp_compute_attention_fu_56_Q_3_address0;
    end else begin
        Q_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_3_address1 = grp_load_and_rearrange_q_fu_92_Q_3_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_3_address1 = grp_compute_attention_fu_56_Q_3_address1;
    end else begin
        Q_3_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_3_ce0 = grp_load_and_rearrange_q_fu_92_Q_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_3_ce0 = grp_compute_attention_fu_56_Q_3_ce0;
    end else begin
        Q_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_3_ce1 = grp_load_and_rearrange_q_fu_92_Q_3_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        Q_3_ce1 = grp_compute_attention_fu_56_Q_3_ce1;
    end else begin
        Q_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_3_we0 = grp_load_and_rearrange_q_fu_92_Q_3_we0;
    end else begin
        Q_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Q_3_we1 = grp_load_and_rearrange_q_fu_92_Q_3_we1;
    end else begin
        Q_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_0_address0 = grp_load_and_rearrange_q_fu_92_V_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        V_0_address0 = grp_compute_attention_fu_56_V_0_address0;
    end else begin
        V_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_0_ce0 = grp_load_and_rearrange_q_fu_92_V_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        V_0_ce0 = grp_compute_attention_fu_56_V_0_ce0;
    end else begin
        V_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_0_ce1 = grp_load_and_rearrange_q_fu_92_V_0_ce1;
    end else begin
        V_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_0_we0 = grp_load_and_rearrange_q_fu_92_V_0_we0;
    end else begin
        V_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_0_we1 = grp_load_and_rearrange_q_fu_92_V_0_we1;
    end else begin
        V_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_1_address0 = grp_load_and_rearrange_q_fu_92_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        V_1_address0 = grp_compute_attention_fu_56_V_1_address0;
    end else begin
        V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_1_ce0 = grp_load_and_rearrange_q_fu_92_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        V_1_ce0 = grp_compute_attention_fu_56_V_1_ce0;
    end else begin
        V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_1_ce1 = grp_load_and_rearrange_q_fu_92_V_1_ce1;
    end else begin
        V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_1_we0 = grp_load_and_rearrange_q_fu_92_V_1_we0;
    end else begin
        V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_1_we1 = grp_load_and_rearrange_q_fu_92_V_1_we1;
    end else begin
        V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_2_address0 = grp_load_and_rearrange_q_fu_92_V_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        V_2_address0 = grp_compute_attention_fu_56_V_2_address0;
    end else begin
        V_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_2_ce0 = grp_load_and_rearrange_q_fu_92_V_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        V_2_ce0 = grp_compute_attention_fu_56_V_2_ce0;
    end else begin
        V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_2_ce1 = grp_load_and_rearrange_q_fu_92_V_2_ce1;
    end else begin
        V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_2_we0 = grp_load_and_rearrange_q_fu_92_V_2_we0;
    end else begin
        V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_2_we1 = grp_load_and_rearrange_q_fu_92_V_2_we1;
    end else begin
        V_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_3_address0 = grp_load_and_rearrange_q_fu_92_V_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        V_3_address0 = grp_compute_attention_fu_56_V_3_address0;
    end else begin
        V_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_3_ce0 = grp_load_and_rearrange_q_fu_92_V_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        V_3_ce0 = grp_compute_attention_fu_56_V_3_ce0;
    end else begin
        V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_3_ce1 = grp_load_and_rearrange_q_fu_92_V_3_ce1;
    end else begin
        V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_3_we0 = grp_load_and_rearrange_q_fu_92_V_3_we0;
    end else begin
        V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        V_3_we1 = grp_load_and_rearrange_q_fu_92_V_3_we1;
    end else begin
        V_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_store_output_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_store_output_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_load_and_rearrange_q_fu_92_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_compute_attention_fu_56_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_store_output_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign grp_compute_attention_fu_56_ap_start = grp_compute_attention_fu_56_ap_start_reg;

assign grp_load_and_rearrange_q_fu_92_ap_start = grp_load_and_rearrange_q_fu_92_ap_start_reg;

assign grp_store_output_fu_122_ap_start = grp_store_output_fu_122_ap_start_reg;

assign input_data_address0 = grp_load_and_rearrange_q_fu_92_input_data_address0;

assign input_data_address1 = grp_load_and_rearrange_q_fu_92_input_data_address1;

assign input_data_ce0 = grp_load_and_rearrange_q_fu_92_input_data_ce0;

assign input_data_ce1 = grp_load_and_rearrange_q_fu_92_input_data_ce1;

assign output_data_address0 = grp_store_output_fu_122_output_data_address0;

assign output_data_address1 = grp_store_output_fu_122_output_data_address1;

assign output_data_ce0 = grp_store_output_fu_122_output_data_ce0;

assign output_data_ce1 = grp_store_output_fu_122_output_data_ce1;

assign output_data_d0 = grp_store_output_fu_122_output_data_d0;

assign output_data_d1 = grp_store_output_fu_122_output_data_d1;

assign output_data_we0 = grp_store_output_fu_122_output_data_we0;

assign output_data_we1 = grp_store_output_fu_122_output_data_we1;

endmodule //top
