-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_data_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    input_data_ce0 : OUT STD_LOGIC;
    input_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    input_data_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    input_data_ce1 : OUT STD_LOGIC;
    input_data_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_data_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_data_ce0 : OUT STD_LOGIC;
    output_data_we0 : OUT STD_LOGIC;
    output_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_data_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    output_data_ce1 : OUT STD_LOGIC;
    output_data_we1 : OUT STD_LOGIC;
    output_data_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of top is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "top,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=19.761000,HLS_SYN_LAT=479500,HLS_SYN_TPT=none,HLS_SYN_MEM=32,HLS_SYN_DSP=14,HLS_SYN_FF=9872,HLS_SYN_LUT=20207,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal Q_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal Q_0_ce0 : STD_LOGIC;
    signal Q_0_we0 : STD_LOGIC;
    signal Q_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Q_0_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal Q_0_ce1 : STD_LOGIC;
    signal Q_0_we1 : STD_LOGIC;
    signal Q_0_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal Q_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal Q_1_ce0 : STD_LOGIC;
    signal Q_1_we0 : STD_LOGIC;
    signal Q_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Q_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal Q_1_ce1 : STD_LOGIC;
    signal Q_1_we1 : STD_LOGIC;
    signal Q_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal Q_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal Q_2_ce0 : STD_LOGIC;
    signal Q_2_we0 : STD_LOGIC;
    signal Q_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Q_2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal Q_2_ce1 : STD_LOGIC;
    signal Q_2_we1 : STD_LOGIC;
    signal Q_2_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal Q_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal Q_3_ce0 : STD_LOGIC;
    signal Q_3_we0 : STD_LOGIC;
    signal Q_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal Q_3_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal Q_3_ce1 : STD_LOGIC;
    signal Q_3_we1 : STD_LOGIC;
    signal Q_3_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal K_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal K_0_ce0 : STD_LOGIC;
    signal K_0_we0 : STD_LOGIC;
    signal K_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal K_0_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal K_0_ce1 : STD_LOGIC;
    signal K_0_we1 : STD_LOGIC;
    signal K_0_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal K_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal K_1_ce0 : STD_LOGIC;
    signal K_1_we0 : STD_LOGIC;
    signal K_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal K_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal K_1_ce1 : STD_LOGIC;
    signal K_1_we1 : STD_LOGIC;
    signal K_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal K_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal K_2_ce0 : STD_LOGIC;
    signal K_2_we0 : STD_LOGIC;
    signal K_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal K_2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal K_2_ce1 : STD_LOGIC;
    signal K_2_we1 : STD_LOGIC;
    signal K_2_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal K_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal K_3_ce0 : STD_LOGIC;
    signal K_3_we0 : STD_LOGIC;
    signal K_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal K_3_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal K_3_ce1 : STD_LOGIC;
    signal K_3_we1 : STD_LOGIC;
    signal K_3_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal V_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal V_0_ce0 : STD_LOGIC;
    signal V_0_we0 : STD_LOGIC;
    signal V_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal V_0_ce1 : STD_LOGIC;
    signal V_0_we1 : STD_LOGIC;
    signal V_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal V_1_ce0 : STD_LOGIC;
    signal V_1_we0 : STD_LOGIC;
    signal V_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal V_1_ce1 : STD_LOGIC;
    signal V_1_we1 : STD_LOGIC;
    signal V_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal V_2_ce0 : STD_LOGIC;
    signal V_2_we0 : STD_LOGIC;
    signal V_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal V_2_ce1 : STD_LOGIC;
    signal V_2_we1 : STD_LOGIC;
    signal V_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal V_3_ce0 : STD_LOGIC;
    signal V_3_we0 : STD_LOGIC;
    signal V_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal V_3_ce1 : STD_LOGIC;
    signal V_3_we1 : STD_LOGIC;
    signal OUT_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal OUT_0_ce0 : STD_LOGIC;
    signal OUT_0_we0 : STD_LOGIC;
    signal OUT_0_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal OUT_0_ce1 : STD_LOGIC;
    signal OUT_0_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal OUT_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal OUT_1_ce0 : STD_LOGIC;
    signal OUT_1_we0 : STD_LOGIC;
    signal OUT_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal OUT_1_ce1 : STD_LOGIC;
    signal OUT_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal OUT_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal OUT_2_ce0 : STD_LOGIC;
    signal OUT_2_we0 : STD_LOGIC;
    signal OUT_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal OUT_2_ce1 : STD_LOGIC;
    signal OUT_2_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal OUT_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal OUT_3_ce0 : STD_LOGIC;
    signal OUT_3_we0 : STD_LOGIC;
    signal OUT_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal OUT_3_ce1 : STD_LOGIC;
    signal OUT_3_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_attention_fu_56_ap_start : STD_LOGIC;
    signal grp_compute_attention_fu_56_ap_done : STD_LOGIC;
    signal grp_compute_attention_fu_56_ap_idle : STD_LOGIC;
    signal grp_compute_attention_fu_56_ap_ready : STD_LOGIC;
    signal grp_compute_attention_fu_56_Q_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_Q_0_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_Q_0_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_Q_0_ce1 : STD_LOGIC;
    signal grp_compute_attention_fu_56_Q_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_Q_1_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_Q_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_Q_1_ce1 : STD_LOGIC;
    signal grp_compute_attention_fu_56_Q_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_Q_2_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_Q_2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_Q_2_ce1 : STD_LOGIC;
    signal grp_compute_attention_fu_56_Q_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_Q_3_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_Q_3_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_Q_3_ce1 : STD_LOGIC;
    signal grp_compute_attention_fu_56_K_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_K_0_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_K_0_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_K_0_ce1 : STD_LOGIC;
    signal grp_compute_attention_fu_56_K_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_K_1_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_K_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_K_1_ce1 : STD_LOGIC;
    signal grp_compute_attention_fu_56_K_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_K_2_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_K_2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_K_2_ce1 : STD_LOGIC;
    signal grp_compute_attention_fu_56_K_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_K_3_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_K_3_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_K_3_ce1 : STD_LOGIC;
    signal grp_compute_attention_fu_56_V_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_V_0_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_V_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_V_1_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_V_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_V_2_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_V_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_V_3_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_OUT_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_OUT_0_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_OUT_0_we0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_OUT_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_attention_fu_56_OUT_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_OUT_1_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_OUT_1_we0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_OUT_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_attention_fu_56_OUT_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_OUT_2_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_OUT_2_we0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_OUT_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_compute_attention_fu_56_OUT_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_compute_attention_fu_56_OUT_3_ce0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_OUT_3_we0 : STD_LOGIC;
    signal grp_compute_attention_fu_56_OUT_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_ap_start : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_ap_done : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_ap_idle : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_ap_ready : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_input_data_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_load_and_rearrange_q_fu_92_input_data_ce0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_input_data_address1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_load_and_rearrange_q_fu_92_input_data_ce1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_0_ce0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_0_we0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_0_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_0_ce1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_0_we1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_0_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_1_ce0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_1_we0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_1_ce1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_1_we1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_1_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_2_ce0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_2_we0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_2_ce1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_2_we1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_2_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_3_ce0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_3_we0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_3_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_Q_3_ce1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_3_we1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_Q_3_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_0_ce0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_0_we0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_0_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_0_ce1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_0_we1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_0_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_1_ce0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_1_we0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_1_ce1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_1_we1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_1_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_2_ce0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_2_we0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_2_ce1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_2_we1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_2_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_3_ce0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_3_we0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_3_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_K_3_ce1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_3_we1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_K_3_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_0_ce0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_0_we0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_0_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_0_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_0_ce1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_0_we1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_0_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_1_ce0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_1_we0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_1_ce1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_1_we1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_1_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_2_ce0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_2_we0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_2_ce1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_2_we1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_2_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_3_ce0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_3_we0 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_3_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_load_and_rearrange_q_fu_92_V_3_ce1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_3_we1 : STD_LOGIC;
    signal grp_load_and_rearrange_q_fu_92_V_3_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_store_output_fu_122_ap_start : STD_LOGIC;
    signal grp_store_output_fu_122_ap_done : STD_LOGIC;
    signal grp_store_output_fu_122_ap_idle : STD_LOGIC;
    signal grp_store_output_fu_122_ap_ready : STD_LOGIC;
    signal grp_store_output_fu_122_output_data_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_store_output_fu_122_output_data_ce0 : STD_LOGIC;
    signal grp_store_output_fu_122_output_data_we0 : STD_LOGIC;
    signal grp_store_output_fu_122_output_data_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_store_output_fu_122_output_data_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_store_output_fu_122_output_data_ce1 : STD_LOGIC;
    signal grp_store_output_fu_122_output_data_we1 : STD_LOGIC;
    signal grp_store_output_fu_122_output_data_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_store_output_fu_122_OUT_0_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_store_output_fu_122_OUT_0_ce0 : STD_LOGIC;
    signal grp_store_output_fu_122_OUT_0_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_store_output_fu_122_OUT_0_ce1 : STD_LOGIC;
    signal grp_store_output_fu_122_OUT_1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_store_output_fu_122_OUT_1_ce0 : STD_LOGIC;
    signal grp_store_output_fu_122_OUT_1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_store_output_fu_122_OUT_1_ce1 : STD_LOGIC;
    signal grp_store_output_fu_122_OUT_2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_store_output_fu_122_OUT_2_ce0 : STD_LOGIC;
    signal grp_store_output_fu_122_OUT_2_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_store_output_fu_122_OUT_2_ce1 : STD_LOGIC;
    signal grp_store_output_fu_122_OUT_3_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_store_output_fu_122_OUT_3_ce0 : STD_LOGIC;
    signal grp_store_output_fu_122_OUT_3_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_store_output_fu_122_OUT_3_ce1 : STD_LOGIC;
    signal grp_compute_attention_fu_56_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_load_and_rearrange_q_fu_92_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_store_output_fu_122_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);

    component compute_attention IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        Q_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_0_ce0 : OUT STD_LOGIC;
        Q_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        Q_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_0_ce1 : OUT STD_LOGIC;
        Q_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        Q_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_1_ce0 : OUT STD_LOGIC;
        Q_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        Q_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_1_ce1 : OUT STD_LOGIC;
        Q_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        Q_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_2_ce0 : OUT STD_LOGIC;
        Q_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        Q_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_2_ce1 : OUT STD_LOGIC;
        Q_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        Q_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_3_ce0 : OUT STD_LOGIC;
        Q_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        Q_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_3_ce1 : OUT STD_LOGIC;
        Q_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        K_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_0_ce0 : OUT STD_LOGIC;
        K_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        K_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_0_ce1 : OUT STD_LOGIC;
        K_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        K_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_1_ce0 : OUT STD_LOGIC;
        K_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        K_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_1_ce1 : OUT STD_LOGIC;
        K_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        K_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_2_ce0 : OUT STD_LOGIC;
        K_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        K_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_2_ce1 : OUT STD_LOGIC;
        K_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        K_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_3_ce0 : OUT STD_LOGIC;
        K_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        K_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_3_ce1 : OUT STD_LOGIC;
        K_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        V_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        V_0_ce0 : OUT STD_LOGIC;
        V_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        V_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        V_1_ce0 : OUT STD_LOGIC;
        V_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        V_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        V_2_ce0 : OUT STD_LOGIC;
        V_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        V_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        V_3_ce0 : OUT STD_LOGIC;
        V_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        OUT_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OUT_0_ce0 : OUT STD_LOGIC;
        OUT_0_we0 : OUT STD_LOGIC;
        OUT_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        OUT_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OUT_1_ce0 : OUT STD_LOGIC;
        OUT_1_we0 : OUT STD_LOGIC;
        OUT_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        OUT_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OUT_2_ce0 : OUT STD_LOGIC;
        OUT_2_we0 : OUT STD_LOGIC;
        OUT_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        OUT_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OUT_3_ce0 : OUT STD_LOGIC;
        OUT_3_we0 : OUT STD_LOGIC;
        OUT_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component load_and_rearrange_q IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_data_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        input_data_ce0 : OUT STD_LOGIC;
        input_data_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_data_address1 : OUT STD_LOGIC_VECTOR (13 downto 0);
        input_data_ce1 : OUT STD_LOGIC;
        input_data_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        Q_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_0_ce0 : OUT STD_LOGIC;
        Q_0_we0 : OUT STD_LOGIC;
        Q_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        Q_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_0_ce1 : OUT STD_LOGIC;
        Q_0_we1 : OUT STD_LOGIC;
        Q_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        Q_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_1_ce0 : OUT STD_LOGIC;
        Q_1_we0 : OUT STD_LOGIC;
        Q_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        Q_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_1_ce1 : OUT STD_LOGIC;
        Q_1_we1 : OUT STD_LOGIC;
        Q_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        Q_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_2_ce0 : OUT STD_LOGIC;
        Q_2_we0 : OUT STD_LOGIC;
        Q_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        Q_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_2_ce1 : OUT STD_LOGIC;
        Q_2_we1 : OUT STD_LOGIC;
        Q_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        Q_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_3_ce0 : OUT STD_LOGIC;
        Q_3_we0 : OUT STD_LOGIC;
        Q_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        Q_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        Q_3_ce1 : OUT STD_LOGIC;
        Q_3_we1 : OUT STD_LOGIC;
        Q_3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        K_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_0_ce0 : OUT STD_LOGIC;
        K_0_we0 : OUT STD_LOGIC;
        K_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        K_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_0_ce1 : OUT STD_LOGIC;
        K_0_we1 : OUT STD_LOGIC;
        K_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        K_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_1_ce0 : OUT STD_LOGIC;
        K_1_we0 : OUT STD_LOGIC;
        K_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        K_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_1_ce1 : OUT STD_LOGIC;
        K_1_we1 : OUT STD_LOGIC;
        K_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        K_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_2_ce0 : OUT STD_LOGIC;
        K_2_we0 : OUT STD_LOGIC;
        K_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        K_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_2_ce1 : OUT STD_LOGIC;
        K_2_we1 : OUT STD_LOGIC;
        K_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        K_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_3_ce0 : OUT STD_LOGIC;
        K_3_we0 : OUT STD_LOGIC;
        K_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        K_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        K_3_ce1 : OUT STD_LOGIC;
        K_3_we1 : OUT STD_LOGIC;
        K_3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        V_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        V_0_ce0 : OUT STD_LOGIC;
        V_0_we0 : OUT STD_LOGIC;
        V_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        V_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        V_0_ce1 : OUT STD_LOGIC;
        V_0_we1 : OUT STD_LOGIC;
        V_0_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        V_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        V_1_ce0 : OUT STD_LOGIC;
        V_1_we0 : OUT STD_LOGIC;
        V_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        V_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        V_1_ce1 : OUT STD_LOGIC;
        V_1_we1 : OUT STD_LOGIC;
        V_1_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        V_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        V_2_ce0 : OUT STD_LOGIC;
        V_2_we0 : OUT STD_LOGIC;
        V_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        V_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        V_2_ce1 : OUT STD_LOGIC;
        V_2_we1 : OUT STD_LOGIC;
        V_2_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        V_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        V_3_ce0 : OUT STD_LOGIC;
        V_3_we0 : OUT STD_LOGIC;
        V_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        V_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        V_3_ce1 : OUT STD_LOGIC;
        V_3_we1 : OUT STD_LOGIC;
        V_3_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component store_output IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_data_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        output_data_ce0 : OUT STD_LOGIC;
        output_data_we0 : OUT STD_LOGIC;
        output_data_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        output_data_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        output_data_ce1 : OUT STD_LOGIC;
        output_data_we1 : OUT STD_LOGIC;
        output_data_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        OUT_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OUT_0_ce0 : OUT STD_LOGIC;
        OUT_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        OUT_0_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OUT_0_ce1 : OUT STD_LOGIC;
        OUT_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        OUT_1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OUT_1_ce0 : OUT STD_LOGIC;
        OUT_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        OUT_1_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OUT_1_ce1 : OUT STD_LOGIC;
        OUT_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        OUT_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OUT_2_ce0 : OUT STD_LOGIC;
        OUT_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        OUT_2_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OUT_2_ce1 : OUT STD_LOGIC;
        OUT_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        OUT_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OUT_3_ce0 : OUT STD_LOGIC;
        OUT_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        OUT_3_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        OUT_3_ce1 : OUT STD_LOGIC;
        OUT_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_Q_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_V_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_OUT_0 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    Q_0_U : component top_Q_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => Q_0_address0,
        ce0 => Q_0_ce0,
        we0 => Q_0_we0,
        d0 => grp_load_and_rearrange_q_fu_92_Q_0_d0,
        q0 => Q_0_q0,
        address1 => Q_0_address1,
        ce1 => Q_0_ce1,
        we1 => Q_0_we1,
        d1 => grp_load_and_rearrange_q_fu_92_Q_0_d1,
        q1 => Q_0_q1);

    Q_1_U : component top_Q_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => Q_1_address0,
        ce0 => Q_1_ce0,
        we0 => Q_1_we0,
        d0 => grp_load_and_rearrange_q_fu_92_Q_1_d0,
        q0 => Q_1_q0,
        address1 => Q_1_address1,
        ce1 => Q_1_ce1,
        we1 => Q_1_we1,
        d1 => grp_load_and_rearrange_q_fu_92_Q_1_d1,
        q1 => Q_1_q1);

    Q_2_U : component top_Q_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => Q_2_address0,
        ce0 => Q_2_ce0,
        we0 => Q_2_we0,
        d0 => grp_load_and_rearrange_q_fu_92_Q_2_d0,
        q0 => Q_2_q0,
        address1 => Q_2_address1,
        ce1 => Q_2_ce1,
        we1 => Q_2_we1,
        d1 => grp_load_and_rearrange_q_fu_92_Q_2_d1,
        q1 => Q_2_q1);

    Q_3_U : component top_Q_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => Q_3_address0,
        ce0 => Q_3_ce0,
        we0 => Q_3_we0,
        d0 => grp_load_and_rearrange_q_fu_92_Q_3_d0,
        q0 => Q_3_q0,
        address1 => Q_3_address1,
        ce1 => Q_3_ce1,
        we1 => Q_3_we1,
        d1 => grp_load_and_rearrange_q_fu_92_Q_3_d1,
        q1 => Q_3_q1);

    K_0_U : component top_Q_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => K_0_address0,
        ce0 => K_0_ce0,
        we0 => K_0_we0,
        d0 => grp_load_and_rearrange_q_fu_92_K_0_d0,
        q0 => K_0_q0,
        address1 => K_0_address1,
        ce1 => K_0_ce1,
        we1 => K_0_we1,
        d1 => grp_load_and_rearrange_q_fu_92_K_0_d1,
        q1 => K_0_q1);

    K_1_U : component top_Q_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => K_1_address0,
        ce0 => K_1_ce0,
        we0 => K_1_we0,
        d0 => grp_load_and_rearrange_q_fu_92_K_1_d0,
        q0 => K_1_q0,
        address1 => K_1_address1,
        ce1 => K_1_ce1,
        we1 => K_1_we1,
        d1 => grp_load_and_rearrange_q_fu_92_K_1_d1,
        q1 => K_1_q1);

    K_2_U : component top_Q_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => K_2_address0,
        ce0 => K_2_ce0,
        we0 => K_2_we0,
        d0 => grp_load_and_rearrange_q_fu_92_K_2_d0,
        q0 => K_2_q0,
        address1 => K_2_address1,
        ce1 => K_2_ce1,
        we1 => K_2_we1,
        d1 => grp_load_and_rearrange_q_fu_92_K_2_d1,
        q1 => K_2_q1);

    K_3_U : component top_Q_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => K_3_address0,
        ce0 => K_3_ce0,
        we0 => K_3_we0,
        d0 => grp_load_and_rearrange_q_fu_92_K_3_d0,
        q0 => K_3_q0,
        address1 => K_3_address1,
        ce1 => K_3_ce1,
        we1 => K_3_we1,
        d1 => grp_load_and_rearrange_q_fu_92_K_3_d1,
        q1 => K_3_q1);

    V_0_U : component top_V_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => V_0_address0,
        ce0 => V_0_ce0,
        we0 => V_0_we0,
        d0 => grp_load_and_rearrange_q_fu_92_V_0_d0,
        q0 => V_0_q0,
        address1 => grp_load_and_rearrange_q_fu_92_V_0_address1,
        ce1 => V_0_ce1,
        we1 => V_0_we1,
        d1 => grp_load_and_rearrange_q_fu_92_V_0_d1);

    V_1_U : component top_V_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => V_1_address0,
        ce0 => V_1_ce0,
        we0 => V_1_we0,
        d0 => grp_load_and_rearrange_q_fu_92_V_1_d0,
        q0 => V_1_q0,
        address1 => grp_load_and_rearrange_q_fu_92_V_1_address1,
        ce1 => V_1_ce1,
        we1 => V_1_we1,
        d1 => grp_load_and_rearrange_q_fu_92_V_1_d1);

    V_2_U : component top_V_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => V_2_address0,
        ce0 => V_2_ce0,
        we0 => V_2_we0,
        d0 => grp_load_and_rearrange_q_fu_92_V_2_d0,
        q0 => V_2_q0,
        address1 => grp_load_and_rearrange_q_fu_92_V_2_address1,
        ce1 => V_2_ce1,
        we1 => V_2_we1,
        d1 => grp_load_and_rearrange_q_fu_92_V_2_d1);

    V_3_U : component top_V_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => V_3_address0,
        ce0 => V_3_ce0,
        we0 => V_3_we0,
        d0 => grp_load_and_rearrange_q_fu_92_V_3_d0,
        q0 => V_3_q0,
        address1 => grp_load_and_rearrange_q_fu_92_V_3_address1,
        ce1 => V_3_ce1,
        we1 => V_3_we1,
        d1 => grp_load_and_rearrange_q_fu_92_V_3_d1);

    OUT_0_U : component top_OUT_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => OUT_0_address0,
        ce0 => OUT_0_ce0,
        we0 => OUT_0_we0,
        d0 => grp_compute_attention_fu_56_OUT_0_d0,
        q0 => OUT_0_q0,
        address1 => grp_store_output_fu_122_OUT_0_address1,
        ce1 => OUT_0_ce1,
        q1 => OUT_0_q1);

    OUT_1_U : component top_OUT_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => OUT_1_address0,
        ce0 => OUT_1_ce0,
        we0 => OUT_1_we0,
        d0 => grp_compute_attention_fu_56_OUT_1_d0,
        q0 => OUT_1_q0,
        address1 => grp_store_output_fu_122_OUT_1_address1,
        ce1 => OUT_1_ce1,
        q1 => OUT_1_q1);

    OUT_2_U : component top_OUT_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => OUT_2_address0,
        ce0 => OUT_2_ce0,
        we0 => OUT_2_we0,
        d0 => grp_compute_attention_fu_56_OUT_2_d0,
        q0 => OUT_2_q0,
        address1 => grp_store_output_fu_122_OUT_2_address1,
        ce1 => OUT_2_ce1,
        q1 => OUT_2_q1);

    OUT_3_U : component top_OUT_0
    generic map (
        DataWidth => 32,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => OUT_3_address0,
        ce0 => OUT_3_ce0,
        we0 => OUT_3_we0,
        d0 => grp_compute_attention_fu_56_OUT_3_d0,
        q0 => OUT_3_q0,
        address1 => grp_store_output_fu_122_OUT_3_address1,
        ce1 => OUT_3_ce1,
        q1 => OUT_3_q1);

    grp_compute_attention_fu_56 : component compute_attention
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_attention_fu_56_ap_start,
        ap_done => grp_compute_attention_fu_56_ap_done,
        ap_idle => grp_compute_attention_fu_56_ap_idle,
        ap_ready => grp_compute_attention_fu_56_ap_ready,
        Q_0_address0 => grp_compute_attention_fu_56_Q_0_address0,
        Q_0_ce0 => grp_compute_attention_fu_56_Q_0_ce0,
        Q_0_q0 => Q_0_q0,
        Q_0_address1 => grp_compute_attention_fu_56_Q_0_address1,
        Q_0_ce1 => grp_compute_attention_fu_56_Q_0_ce1,
        Q_0_q1 => Q_0_q1,
        Q_1_address0 => grp_compute_attention_fu_56_Q_1_address0,
        Q_1_ce0 => grp_compute_attention_fu_56_Q_1_ce0,
        Q_1_q0 => Q_1_q0,
        Q_1_address1 => grp_compute_attention_fu_56_Q_1_address1,
        Q_1_ce1 => grp_compute_attention_fu_56_Q_1_ce1,
        Q_1_q1 => Q_1_q1,
        Q_2_address0 => grp_compute_attention_fu_56_Q_2_address0,
        Q_2_ce0 => grp_compute_attention_fu_56_Q_2_ce0,
        Q_2_q0 => Q_2_q0,
        Q_2_address1 => grp_compute_attention_fu_56_Q_2_address1,
        Q_2_ce1 => grp_compute_attention_fu_56_Q_2_ce1,
        Q_2_q1 => Q_2_q1,
        Q_3_address0 => grp_compute_attention_fu_56_Q_3_address0,
        Q_3_ce0 => grp_compute_attention_fu_56_Q_3_ce0,
        Q_3_q0 => Q_3_q0,
        Q_3_address1 => grp_compute_attention_fu_56_Q_3_address1,
        Q_3_ce1 => grp_compute_attention_fu_56_Q_3_ce1,
        Q_3_q1 => Q_3_q1,
        K_0_address0 => grp_compute_attention_fu_56_K_0_address0,
        K_0_ce0 => grp_compute_attention_fu_56_K_0_ce0,
        K_0_q0 => K_0_q0,
        K_0_address1 => grp_compute_attention_fu_56_K_0_address1,
        K_0_ce1 => grp_compute_attention_fu_56_K_0_ce1,
        K_0_q1 => K_0_q1,
        K_1_address0 => grp_compute_attention_fu_56_K_1_address0,
        K_1_ce0 => grp_compute_attention_fu_56_K_1_ce0,
        K_1_q0 => K_1_q0,
        K_1_address1 => grp_compute_attention_fu_56_K_1_address1,
        K_1_ce1 => grp_compute_attention_fu_56_K_1_ce1,
        K_1_q1 => K_1_q1,
        K_2_address0 => grp_compute_attention_fu_56_K_2_address0,
        K_2_ce0 => grp_compute_attention_fu_56_K_2_ce0,
        K_2_q0 => K_2_q0,
        K_2_address1 => grp_compute_attention_fu_56_K_2_address1,
        K_2_ce1 => grp_compute_attention_fu_56_K_2_ce1,
        K_2_q1 => K_2_q1,
        K_3_address0 => grp_compute_attention_fu_56_K_3_address0,
        K_3_ce0 => grp_compute_attention_fu_56_K_3_ce0,
        K_3_q0 => K_3_q0,
        K_3_address1 => grp_compute_attention_fu_56_K_3_address1,
        K_3_ce1 => grp_compute_attention_fu_56_K_3_ce1,
        K_3_q1 => K_3_q1,
        V_0_address0 => grp_compute_attention_fu_56_V_0_address0,
        V_0_ce0 => grp_compute_attention_fu_56_V_0_ce0,
        V_0_q0 => V_0_q0,
        V_1_address0 => grp_compute_attention_fu_56_V_1_address0,
        V_1_ce0 => grp_compute_attention_fu_56_V_1_ce0,
        V_1_q0 => V_1_q0,
        V_2_address0 => grp_compute_attention_fu_56_V_2_address0,
        V_2_ce0 => grp_compute_attention_fu_56_V_2_ce0,
        V_2_q0 => V_2_q0,
        V_3_address0 => grp_compute_attention_fu_56_V_3_address0,
        V_3_ce0 => grp_compute_attention_fu_56_V_3_ce0,
        V_3_q0 => V_3_q0,
        OUT_0_address0 => grp_compute_attention_fu_56_OUT_0_address0,
        OUT_0_ce0 => grp_compute_attention_fu_56_OUT_0_ce0,
        OUT_0_we0 => grp_compute_attention_fu_56_OUT_0_we0,
        OUT_0_d0 => grp_compute_attention_fu_56_OUT_0_d0,
        OUT_1_address0 => grp_compute_attention_fu_56_OUT_1_address0,
        OUT_1_ce0 => grp_compute_attention_fu_56_OUT_1_ce0,
        OUT_1_we0 => grp_compute_attention_fu_56_OUT_1_we0,
        OUT_1_d0 => grp_compute_attention_fu_56_OUT_1_d0,
        OUT_2_address0 => grp_compute_attention_fu_56_OUT_2_address0,
        OUT_2_ce0 => grp_compute_attention_fu_56_OUT_2_ce0,
        OUT_2_we0 => grp_compute_attention_fu_56_OUT_2_we0,
        OUT_2_d0 => grp_compute_attention_fu_56_OUT_2_d0,
        OUT_3_address0 => grp_compute_attention_fu_56_OUT_3_address0,
        OUT_3_ce0 => grp_compute_attention_fu_56_OUT_3_ce0,
        OUT_3_we0 => grp_compute_attention_fu_56_OUT_3_we0,
        OUT_3_d0 => grp_compute_attention_fu_56_OUT_3_d0);

    grp_load_and_rearrange_q_fu_92 : component load_and_rearrange_q
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_load_and_rearrange_q_fu_92_ap_start,
        ap_done => grp_load_and_rearrange_q_fu_92_ap_done,
        ap_idle => grp_load_and_rearrange_q_fu_92_ap_idle,
        ap_ready => grp_load_and_rearrange_q_fu_92_ap_ready,
        input_data_address0 => grp_load_and_rearrange_q_fu_92_input_data_address0,
        input_data_ce0 => grp_load_and_rearrange_q_fu_92_input_data_ce0,
        input_data_q0 => input_data_q0,
        input_data_address1 => grp_load_and_rearrange_q_fu_92_input_data_address1,
        input_data_ce1 => grp_load_and_rearrange_q_fu_92_input_data_ce1,
        input_data_q1 => input_data_q1,
        Q_0_address0 => grp_load_and_rearrange_q_fu_92_Q_0_address0,
        Q_0_ce0 => grp_load_and_rearrange_q_fu_92_Q_0_ce0,
        Q_0_we0 => grp_load_and_rearrange_q_fu_92_Q_0_we0,
        Q_0_d0 => grp_load_and_rearrange_q_fu_92_Q_0_d0,
        Q_0_address1 => grp_load_and_rearrange_q_fu_92_Q_0_address1,
        Q_0_ce1 => grp_load_and_rearrange_q_fu_92_Q_0_ce1,
        Q_0_we1 => grp_load_and_rearrange_q_fu_92_Q_0_we1,
        Q_0_d1 => grp_load_and_rearrange_q_fu_92_Q_0_d1,
        Q_1_address0 => grp_load_and_rearrange_q_fu_92_Q_1_address0,
        Q_1_ce0 => grp_load_and_rearrange_q_fu_92_Q_1_ce0,
        Q_1_we0 => grp_load_and_rearrange_q_fu_92_Q_1_we0,
        Q_1_d0 => grp_load_and_rearrange_q_fu_92_Q_1_d0,
        Q_1_address1 => grp_load_and_rearrange_q_fu_92_Q_1_address1,
        Q_1_ce1 => grp_load_and_rearrange_q_fu_92_Q_1_ce1,
        Q_1_we1 => grp_load_and_rearrange_q_fu_92_Q_1_we1,
        Q_1_d1 => grp_load_and_rearrange_q_fu_92_Q_1_d1,
        Q_2_address0 => grp_load_and_rearrange_q_fu_92_Q_2_address0,
        Q_2_ce0 => grp_load_and_rearrange_q_fu_92_Q_2_ce0,
        Q_2_we0 => grp_load_and_rearrange_q_fu_92_Q_2_we0,
        Q_2_d0 => grp_load_and_rearrange_q_fu_92_Q_2_d0,
        Q_2_address1 => grp_load_and_rearrange_q_fu_92_Q_2_address1,
        Q_2_ce1 => grp_load_and_rearrange_q_fu_92_Q_2_ce1,
        Q_2_we1 => grp_load_and_rearrange_q_fu_92_Q_2_we1,
        Q_2_d1 => grp_load_and_rearrange_q_fu_92_Q_2_d1,
        Q_3_address0 => grp_load_and_rearrange_q_fu_92_Q_3_address0,
        Q_3_ce0 => grp_load_and_rearrange_q_fu_92_Q_3_ce0,
        Q_3_we0 => grp_load_and_rearrange_q_fu_92_Q_3_we0,
        Q_3_d0 => grp_load_and_rearrange_q_fu_92_Q_3_d0,
        Q_3_address1 => grp_load_and_rearrange_q_fu_92_Q_3_address1,
        Q_3_ce1 => grp_load_and_rearrange_q_fu_92_Q_3_ce1,
        Q_3_we1 => grp_load_and_rearrange_q_fu_92_Q_3_we1,
        Q_3_d1 => grp_load_and_rearrange_q_fu_92_Q_3_d1,
        K_0_address0 => grp_load_and_rearrange_q_fu_92_K_0_address0,
        K_0_ce0 => grp_load_and_rearrange_q_fu_92_K_0_ce0,
        K_0_we0 => grp_load_and_rearrange_q_fu_92_K_0_we0,
        K_0_d0 => grp_load_and_rearrange_q_fu_92_K_0_d0,
        K_0_address1 => grp_load_and_rearrange_q_fu_92_K_0_address1,
        K_0_ce1 => grp_load_and_rearrange_q_fu_92_K_0_ce1,
        K_0_we1 => grp_load_and_rearrange_q_fu_92_K_0_we1,
        K_0_d1 => grp_load_and_rearrange_q_fu_92_K_0_d1,
        K_1_address0 => grp_load_and_rearrange_q_fu_92_K_1_address0,
        K_1_ce0 => grp_load_and_rearrange_q_fu_92_K_1_ce0,
        K_1_we0 => grp_load_and_rearrange_q_fu_92_K_1_we0,
        K_1_d0 => grp_load_and_rearrange_q_fu_92_K_1_d0,
        K_1_address1 => grp_load_and_rearrange_q_fu_92_K_1_address1,
        K_1_ce1 => grp_load_and_rearrange_q_fu_92_K_1_ce1,
        K_1_we1 => grp_load_and_rearrange_q_fu_92_K_1_we1,
        K_1_d1 => grp_load_and_rearrange_q_fu_92_K_1_d1,
        K_2_address0 => grp_load_and_rearrange_q_fu_92_K_2_address0,
        K_2_ce0 => grp_load_and_rearrange_q_fu_92_K_2_ce0,
        K_2_we0 => grp_load_and_rearrange_q_fu_92_K_2_we0,
        K_2_d0 => grp_load_and_rearrange_q_fu_92_K_2_d0,
        K_2_address1 => grp_load_and_rearrange_q_fu_92_K_2_address1,
        K_2_ce1 => grp_load_and_rearrange_q_fu_92_K_2_ce1,
        K_2_we1 => grp_load_and_rearrange_q_fu_92_K_2_we1,
        K_2_d1 => grp_load_and_rearrange_q_fu_92_K_2_d1,
        K_3_address0 => grp_load_and_rearrange_q_fu_92_K_3_address0,
        K_3_ce0 => grp_load_and_rearrange_q_fu_92_K_3_ce0,
        K_3_we0 => grp_load_and_rearrange_q_fu_92_K_3_we0,
        K_3_d0 => grp_load_and_rearrange_q_fu_92_K_3_d0,
        K_3_address1 => grp_load_and_rearrange_q_fu_92_K_3_address1,
        K_3_ce1 => grp_load_and_rearrange_q_fu_92_K_3_ce1,
        K_3_we1 => grp_load_and_rearrange_q_fu_92_K_3_we1,
        K_3_d1 => grp_load_and_rearrange_q_fu_92_K_3_d1,
        V_0_address0 => grp_load_and_rearrange_q_fu_92_V_0_address0,
        V_0_ce0 => grp_load_and_rearrange_q_fu_92_V_0_ce0,
        V_0_we0 => grp_load_and_rearrange_q_fu_92_V_0_we0,
        V_0_d0 => grp_load_and_rearrange_q_fu_92_V_0_d0,
        V_0_address1 => grp_load_and_rearrange_q_fu_92_V_0_address1,
        V_0_ce1 => grp_load_and_rearrange_q_fu_92_V_0_ce1,
        V_0_we1 => grp_load_and_rearrange_q_fu_92_V_0_we1,
        V_0_d1 => grp_load_and_rearrange_q_fu_92_V_0_d1,
        V_1_address0 => grp_load_and_rearrange_q_fu_92_V_1_address0,
        V_1_ce0 => grp_load_and_rearrange_q_fu_92_V_1_ce0,
        V_1_we0 => grp_load_and_rearrange_q_fu_92_V_1_we0,
        V_1_d0 => grp_load_and_rearrange_q_fu_92_V_1_d0,
        V_1_address1 => grp_load_and_rearrange_q_fu_92_V_1_address1,
        V_1_ce1 => grp_load_and_rearrange_q_fu_92_V_1_ce1,
        V_1_we1 => grp_load_and_rearrange_q_fu_92_V_1_we1,
        V_1_d1 => grp_load_and_rearrange_q_fu_92_V_1_d1,
        V_2_address0 => grp_load_and_rearrange_q_fu_92_V_2_address0,
        V_2_ce0 => grp_load_and_rearrange_q_fu_92_V_2_ce0,
        V_2_we0 => grp_load_and_rearrange_q_fu_92_V_2_we0,
        V_2_d0 => grp_load_and_rearrange_q_fu_92_V_2_d0,
        V_2_address1 => grp_load_and_rearrange_q_fu_92_V_2_address1,
        V_2_ce1 => grp_load_and_rearrange_q_fu_92_V_2_ce1,
        V_2_we1 => grp_load_and_rearrange_q_fu_92_V_2_we1,
        V_2_d1 => grp_load_and_rearrange_q_fu_92_V_2_d1,
        V_3_address0 => grp_load_and_rearrange_q_fu_92_V_3_address0,
        V_3_ce0 => grp_load_and_rearrange_q_fu_92_V_3_ce0,
        V_3_we0 => grp_load_and_rearrange_q_fu_92_V_3_we0,
        V_3_d0 => grp_load_and_rearrange_q_fu_92_V_3_d0,
        V_3_address1 => grp_load_and_rearrange_q_fu_92_V_3_address1,
        V_3_ce1 => grp_load_and_rearrange_q_fu_92_V_3_ce1,
        V_3_we1 => grp_load_and_rearrange_q_fu_92_V_3_we1,
        V_3_d1 => grp_load_and_rearrange_q_fu_92_V_3_d1);

    grp_store_output_fu_122 : component store_output
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_store_output_fu_122_ap_start,
        ap_done => grp_store_output_fu_122_ap_done,
        ap_idle => grp_store_output_fu_122_ap_idle,
        ap_ready => grp_store_output_fu_122_ap_ready,
        output_data_address0 => grp_store_output_fu_122_output_data_address0,
        output_data_ce0 => grp_store_output_fu_122_output_data_ce0,
        output_data_we0 => grp_store_output_fu_122_output_data_we0,
        output_data_d0 => grp_store_output_fu_122_output_data_d0,
        output_data_address1 => grp_store_output_fu_122_output_data_address1,
        output_data_ce1 => grp_store_output_fu_122_output_data_ce1,
        output_data_we1 => grp_store_output_fu_122_output_data_we1,
        output_data_d1 => grp_store_output_fu_122_output_data_d1,
        OUT_0_address0 => grp_store_output_fu_122_OUT_0_address0,
        OUT_0_ce0 => grp_store_output_fu_122_OUT_0_ce0,
        OUT_0_q0 => OUT_0_q0,
        OUT_0_address1 => grp_store_output_fu_122_OUT_0_address1,
        OUT_0_ce1 => grp_store_output_fu_122_OUT_0_ce1,
        OUT_0_q1 => OUT_0_q1,
        OUT_1_address0 => grp_store_output_fu_122_OUT_1_address0,
        OUT_1_ce0 => grp_store_output_fu_122_OUT_1_ce0,
        OUT_1_q0 => OUT_1_q0,
        OUT_1_address1 => grp_store_output_fu_122_OUT_1_address1,
        OUT_1_ce1 => grp_store_output_fu_122_OUT_1_ce1,
        OUT_1_q1 => OUT_1_q1,
        OUT_2_address0 => grp_store_output_fu_122_OUT_2_address0,
        OUT_2_ce0 => grp_store_output_fu_122_OUT_2_ce0,
        OUT_2_q0 => OUT_2_q0,
        OUT_2_address1 => grp_store_output_fu_122_OUT_2_address1,
        OUT_2_ce1 => grp_store_output_fu_122_OUT_2_ce1,
        OUT_2_q1 => OUT_2_q1,
        OUT_3_address0 => grp_store_output_fu_122_OUT_3_address0,
        OUT_3_ce0 => grp_store_output_fu_122_OUT_3_ce0,
        OUT_3_q0 => OUT_3_q0,
        OUT_3_address1 => grp_store_output_fu_122_OUT_3_address1,
        OUT_3_ce1 => grp_store_output_fu_122_OUT_3_ce1,
        OUT_3_q1 => OUT_3_q1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_compute_attention_fu_56_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_attention_fu_56_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_compute_attention_fu_56_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_attention_fu_56_ap_ready = ap_const_logic_1)) then 
                    grp_compute_attention_fu_56_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_load_and_rearrange_q_fu_92_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_load_and_rearrange_q_fu_92_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_load_and_rearrange_q_fu_92_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_load_and_rearrange_q_fu_92_ap_ready = ap_const_logic_1)) then 
                    grp_load_and_rearrange_q_fu_92_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_store_output_fu_122_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_store_output_fu_122_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_store_output_fu_122_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_store_output_fu_122_ap_ready = ap_const_logic_1)) then 
                    grp_store_output_fu_122_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_compute_attention_fu_56_ap_done, grp_load_and_rearrange_q_fu_92_ap_done, grp_store_output_fu_122_ap_done, ap_CS_fsm_state4, ap_CS_fsm_state2, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_load_and_rearrange_q_fu_92_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_compute_attention_fu_56_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_store_output_fu_122_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;

    K_0_address0_assign_proc : process(grp_compute_attention_fu_56_K_0_address0, grp_load_and_rearrange_q_fu_92_K_0_address0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_0_address0 <= grp_load_and_rearrange_q_fu_92_K_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_0_address0 <= grp_compute_attention_fu_56_K_0_address0;
        else 
            K_0_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    K_0_address1_assign_proc : process(grp_compute_attention_fu_56_K_0_address1, grp_load_and_rearrange_q_fu_92_K_0_address1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_0_address1 <= grp_load_and_rearrange_q_fu_92_K_0_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_0_address1 <= grp_compute_attention_fu_56_K_0_address1;
        else 
            K_0_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    K_0_ce0_assign_proc : process(grp_compute_attention_fu_56_K_0_ce0, grp_load_and_rearrange_q_fu_92_K_0_ce0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_0_ce0 <= grp_load_and_rearrange_q_fu_92_K_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_0_ce0 <= grp_compute_attention_fu_56_K_0_ce0;
        else 
            K_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    K_0_ce1_assign_proc : process(grp_compute_attention_fu_56_K_0_ce1, grp_load_and_rearrange_q_fu_92_K_0_ce1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_0_ce1 <= grp_load_and_rearrange_q_fu_92_K_0_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_0_ce1 <= grp_compute_attention_fu_56_K_0_ce1;
        else 
            K_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    K_0_we0_assign_proc : process(grp_load_and_rearrange_q_fu_92_K_0_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_0_we0 <= grp_load_and_rearrange_q_fu_92_K_0_we0;
        else 
            K_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    K_0_we1_assign_proc : process(grp_load_and_rearrange_q_fu_92_K_0_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_0_we1 <= grp_load_and_rearrange_q_fu_92_K_0_we1;
        else 
            K_0_we1 <= ap_const_logic_0;
        end if; 
    end process;


    K_1_address0_assign_proc : process(grp_compute_attention_fu_56_K_1_address0, grp_load_and_rearrange_q_fu_92_K_1_address0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_1_address0 <= grp_load_and_rearrange_q_fu_92_K_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_1_address0 <= grp_compute_attention_fu_56_K_1_address0;
        else 
            K_1_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    K_1_address1_assign_proc : process(grp_compute_attention_fu_56_K_1_address1, grp_load_and_rearrange_q_fu_92_K_1_address1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_1_address1 <= grp_load_and_rearrange_q_fu_92_K_1_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_1_address1 <= grp_compute_attention_fu_56_K_1_address1;
        else 
            K_1_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    K_1_ce0_assign_proc : process(grp_compute_attention_fu_56_K_1_ce0, grp_load_and_rearrange_q_fu_92_K_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_1_ce0 <= grp_load_and_rearrange_q_fu_92_K_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_1_ce0 <= grp_compute_attention_fu_56_K_1_ce0;
        else 
            K_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    K_1_ce1_assign_proc : process(grp_compute_attention_fu_56_K_1_ce1, grp_load_and_rearrange_q_fu_92_K_1_ce1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_1_ce1 <= grp_load_and_rearrange_q_fu_92_K_1_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_1_ce1 <= grp_compute_attention_fu_56_K_1_ce1;
        else 
            K_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    K_1_we0_assign_proc : process(grp_load_and_rearrange_q_fu_92_K_1_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_1_we0 <= grp_load_and_rearrange_q_fu_92_K_1_we0;
        else 
            K_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    K_1_we1_assign_proc : process(grp_load_and_rearrange_q_fu_92_K_1_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_1_we1 <= grp_load_and_rearrange_q_fu_92_K_1_we1;
        else 
            K_1_we1 <= ap_const_logic_0;
        end if; 
    end process;


    K_2_address0_assign_proc : process(grp_compute_attention_fu_56_K_2_address0, grp_load_and_rearrange_q_fu_92_K_2_address0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_2_address0 <= grp_load_and_rearrange_q_fu_92_K_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_2_address0 <= grp_compute_attention_fu_56_K_2_address0;
        else 
            K_2_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    K_2_address1_assign_proc : process(grp_compute_attention_fu_56_K_2_address1, grp_load_and_rearrange_q_fu_92_K_2_address1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_2_address1 <= grp_load_and_rearrange_q_fu_92_K_2_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_2_address1 <= grp_compute_attention_fu_56_K_2_address1;
        else 
            K_2_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    K_2_ce0_assign_proc : process(grp_compute_attention_fu_56_K_2_ce0, grp_load_and_rearrange_q_fu_92_K_2_ce0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_2_ce0 <= grp_load_and_rearrange_q_fu_92_K_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_2_ce0 <= grp_compute_attention_fu_56_K_2_ce0;
        else 
            K_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    K_2_ce1_assign_proc : process(grp_compute_attention_fu_56_K_2_ce1, grp_load_and_rearrange_q_fu_92_K_2_ce1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_2_ce1 <= grp_load_and_rearrange_q_fu_92_K_2_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_2_ce1 <= grp_compute_attention_fu_56_K_2_ce1;
        else 
            K_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    K_2_we0_assign_proc : process(grp_load_and_rearrange_q_fu_92_K_2_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_2_we0 <= grp_load_and_rearrange_q_fu_92_K_2_we0;
        else 
            K_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    K_2_we1_assign_proc : process(grp_load_and_rearrange_q_fu_92_K_2_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_2_we1 <= grp_load_and_rearrange_q_fu_92_K_2_we1;
        else 
            K_2_we1 <= ap_const_logic_0;
        end if; 
    end process;


    K_3_address0_assign_proc : process(grp_compute_attention_fu_56_K_3_address0, grp_load_and_rearrange_q_fu_92_K_3_address0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_3_address0 <= grp_load_and_rearrange_q_fu_92_K_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_3_address0 <= grp_compute_attention_fu_56_K_3_address0;
        else 
            K_3_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    K_3_address1_assign_proc : process(grp_compute_attention_fu_56_K_3_address1, grp_load_and_rearrange_q_fu_92_K_3_address1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_3_address1 <= grp_load_and_rearrange_q_fu_92_K_3_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_3_address1 <= grp_compute_attention_fu_56_K_3_address1;
        else 
            K_3_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    K_3_ce0_assign_proc : process(grp_compute_attention_fu_56_K_3_ce0, grp_load_and_rearrange_q_fu_92_K_3_ce0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_3_ce0 <= grp_load_and_rearrange_q_fu_92_K_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_3_ce0 <= grp_compute_attention_fu_56_K_3_ce0;
        else 
            K_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    K_3_ce1_assign_proc : process(grp_compute_attention_fu_56_K_3_ce1, grp_load_and_rearrange_q_fu_92_K_3_ce1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_3_ce1 <= grp_load_and_rearrange_q_fu_92_K_3_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            K_3_ce1 <= grp_compute_attention_fu_56_K_3_ce1;
        else 
            K_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    K_3_we0_assign_proc : process(grp_load_and_rearrange_q_fu_92_K_3_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_3_we0 <= grp_load_and_rearrange_q_fu_92_K_3_we0;
        else 
            K_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    K_3_we1_assign_proc : process(grp_load_and_rearrange_q_fu_92_K_3_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            K_3_we1 <= grp_load_and_rearrange_q_fu_92_K_3_we1;
        else 
            K_3_we1 <= ap_const_logic_0;
        end if; 
    end process;


    OUT_0_address0_assign_proc : process(grp_compute_attention_fu_56_OUT_0_address0, grp_store_output_fu_122_OUT_0_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OUT_0_address0 <= grp_store_output_fu_122_OUT_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OUT_0_address0 <= grp_compute_attention_fu_56_OUT_0_address0;
        else 
            OUT_0_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    OUT_0_ce0_assign_proc : process(grp_compute_attention_fu_56_OUT_0_ce0, grp_store_output_fu_122_OUT_0_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OUT_0_ce0 <= grp_store_output_fu_122_OUT_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OUT_0_ce0 <= grp_compute_attention_fu_56_OUT_0_ce0;
        else 
            OUT_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    OUT_0_ce1_assign_proc : process(grp_store_output_fu_122_OUT_0_ce1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OUT_0_ce1 <= grp_store_output_fu_122_OUT_0_ce1;
        else 
            OUT_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    OUT_0_we0_assign_proc : process(grp_compute_attention_fu_56_OUT_0_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OUT_0_we0 <= grp_compute_attention_fu_56_OUT_0_we0;
        else 
            OUT_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    OUT_1_address0_assign_proc : process(grp_compute_attention_fu_56_OUT_1_address0, grp_store_output_fu_122_OUT_1_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OUT_1_address0 <= grp_store_output_fu_122_OUT_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OUT_1_address0 <= grp_compute_attention_fu_56_OUT_1_address0;
        else 
            OUT_1_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    OUT_1_ce0_assign_proc : process(grp_compute_attention_fu_56_OUT_1_ce0, grp_store_output_fu_122_OUT_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OUT_1_ce0 <= grp_store_output_fu_122_OUT_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OUT_1_ce0 <= grp_compute_attention_fu_56_OUT_1_ce0;
        else 
            OUT_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    OUT_1_ce1_assign_proc : process(grp_store_output_fu_122_OUT_1_ce1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OUT_1_ce1 <= grp_store_output_fu_122_OUT_1_ce1;
        else 
            OUT_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    OUT_1_we0_assign_proc : process(grp_compute_attention_fu_56_OUT_1_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OUT_1_we0 <= grp_compute_attention_fu_56_OUT_1_we0;
        else 
            OUT_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    OUT_2_address0_assign_proc : process(grp_compute_attention_fu_56_OUT_2_address0, grp_store_output_fu_122_OUT_2_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OUT_2_address0 <= grp_store_output_fu_122_OUT_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OUT_2_address0 <= grp_compute_attention_fu_56_OUT_2_address0;
        else 
            OUT_2_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    OUT_2_ce0_assign_proc : process(grp_compute_attention_fu_56_OUT_2_ce0, grp_store_output_fu_122_OUT_2_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OUT_2_ce0 <= grp_store_output_fu_122_OUT_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OUT_2_ce0 <= grp_compute_attention_fu_56_OUT_2_ce0;
        else 
            OUT_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    OUT_2_ce1_assign_proc : process(grp_store_output_fu_122_OUT_2_ce1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OUT_2_ce1 <= grp_store_output_fu_122_OUT_2_ce1;
        else 
            OUT_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    OUT_2_we0_assign_proc : process(grp_compute_attention_fu_56_OUT_2_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OUT_2_we0 <= grp_compute_attention_fu_56_OUT_2_we0;
        else 
            OUT_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    OUT_3_address0_assign_proc : process(grp_compute_attention_fu_56_OUT_3_address0, grp_store_output_fu_122_OUT_3_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OUT_3_address0 <= grp_store_output_fu_122_OUT_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OUT_3_address0 <= grp_compute_attention_fu_56_OUT_3_address0;
        else 
            OUT_3_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    OUT_3_ce0_assign_proc : process(grp_compute_attention_fu_56_OUT_3_ce0, grp_store_output_fu_122_OUT_3_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OUT_3_ce0 <= grp_store_output_fu_122_OUT_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OUT_3_ce0 <= grp_compute_attention_fu_56_OUT_3_ce0;
        else 
            OUT_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    OUT_3_ce1_assign_proc : process(grp_store_output_fu_122_OUT_3_ce1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            OUT_3_ce1 <= grp_store_output_fu_122_OUT_3_ce1;
        else 
            OUT_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    OUT_3_we0_assign_proc : process(grp_compute_attention_fu_56_OUT_3_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            OUT_3_we0 <= grp_compute_attention_fu_56_OUT_3_we0;
        else 
            OUT_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    Q_0_address0_assign_proc : process(grp_compute_attention_fu_56_Q_0_address0, grp_load_and_rearrange_q_fu_92_Q_0_address0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_0_address0 <= grp_load_and_rearrange_q_fu_92_Q_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_0_address0 <= grp_compute_attention_fu_56_Q_0_address0;
        else 
            Q_0_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    Q_0_address1_assign_proc : process(grp_compute_attention_fu_56_Q_0_address1, grp_load_and_rearrange_q_fu_92_Q_0_address1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_0_address1 <= grp_load_and_rearrange_q_fu_92_Q_0_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_0_address1 <= grp_compute_attention_fu_56_Q_0_address1;
        else 
            Q_0_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    Q_0_ce0_assign_proc : process(grp_compute_attention_fu_56_Q_0_ce0, grp_load_and_rearrange_q_fu_92_Q_0_ce0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_0_ce0 <= grp_load_and_rearrange_q_fu_92_Q_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_0_ce0 <= grp_compute_attention_fu_56_Q_0_ce0;
        else 
            Q_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    Q_0_ce1_assign_proc : process(grp_compute_attention_fu_56_Q_0_ce1, grp_load_and_rearrange_q_fu_92_Q_0_ce1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_0_ce1 <= grp_load_and_rearrange_q_fu_92_Q_0_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_0_ce1 <= grp_compute_attention_fu_56_Q_0_ce1;
        else 
            Q_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    Q_0_we0_assign_proc : process(grp_load_and_rearrange_q_fu_92_Q_0_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_0_we0 <= grp_load_and_rearrange_q_fu_92_Q_0_we0;
        else 
            Q_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    Q_0_we1_assign_proc : process(grp_load_and_rearrange_q_fu_92_Q_0_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_0_we1 <= grp_load_and_rearrange_q_fu_92_Q_0_we1;
        else 
            Q_0_we1 <= ap_const_logic_0;
        end if; 
    end process;


    Q_1_address0_assign_proc : process(grp_compute_attention_fu_56_Q_1_address0, grp_load_and_rearrange_q_fu_92_Q_1_address0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_1_address0 <= grp_load_and_rearrange_q_fu_92_Q_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_1_address0 <= grp_compute_attention_fu_56_Q_1_address0;
        else 
            Q_1_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    Q_1_address1_assign_proc : process(grp_compute_attention_fu_56_Q_1_address1, grp_load_and_rearrange_q_fu_92_Q_1_address1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_1_address1 <= grp_load_and_rearrange_q_fu_92_Q_1_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_1_address1 <= grp_compute_attention_fu_56_Q_1_address1;
        else 
            Q_1_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    Q_1_ce0_assign_proc : process(grp_compute_attention_fu_56_Q_1_ce0, grp_load_and_rearrange_q_fu_92_Q_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_1_ce0 <= grp_load_and_rearrange_q_fu_92_Q_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_1_ce0 <= grp_compute_attention_fu_56_Q_1_ce0;
        else 
            Q_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    Q_1_ce1_assign_proc : process(grp_compute_attention_fu_56_Q_1_ce1, grp_load_and_rearrange_q_fu_92_Q_1_ce1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_1_ce1 <= grp_load_and_rearrange_q_fu_92_Q_1_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_1_ce1 <= grp_compute_attention_fu_56_Q_1_ce1;
        else 
            Q_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    Q_1_we0_assign_proc : process(grp_load_and_rearrange_q_fu_92_Q_1_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_1_we0 <= grp_load_and_rearrange_q_fu_92_Q_1_we0;
        else 
            Q_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    Q_1_we1_assign_proc : process(grp_load_and_rearrange_q_fu_92_Q_1_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_1_we1 <= grp_load_and_rearrange_q_fu_92_Q_1_we1;
        else 
            Q_1_we1 <= ap_const_logic_0;
        end if; 
    end process;


    Q_2_address0_assign_proc : process(grp_compute_attention_fu_56_Q_2_address0, grp_load_and_rearrange_q_fu_92_Q_2_address0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_2_address0 <= grp_load_and_rearrange_q_fu_92_Q_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_2_address0 <= grp_compute_attention_fu_56_Q_2_address0;
        else 
            Q_2_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    Q_2_address1_assign_proc : process(grp_compute_attention_fu_56_Q_2_address1, grp_load_and_rearrange_q_fu_92_Q_2_address1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_2_address1 <= grp_load_and_rearrange_q_fu_92_Q_2_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_2_address1 <= grp_compute_attention_fu_56_Q_2_address1;
        else 
            Q_2_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    Q_2_ce0_assign_proc : process(grp_compute_attention_fu_56_Q_2_ce0, grp_load_and_rearrange_q_fu_92_Q_2_ce0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_2_ce0 <= grp_load_and_rearrange_q_fu_92_Q_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_2_ce0 <= grp_compute_attention_fu_56_Q_2_ce0;
        else 
            Q_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    Q_2_ce1_assign_proc : process(grp_compute_attention_fu_56_Q_2_ce1, grp_load_and_rearrange_q_fu_92_Q_2_ce1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_2_ce1 <= grp_load_and_rearrange_q_fu_92_Q_2_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_2_ce1 <= grp_compute_attention_fu_56_Q_2_ce1;
        else 
            Q_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    Q_2_we0_assign_proc : process(grp_load_and_rearrange_q_fu_92_Q_2_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_2_we0 <= grp_load_and_rearrange_q_fu_92_Q_2_we0;
        else 
            Q_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    Q_2_we1_assign_proc : process(grp_load_and_rearrange_q_fu_92_Q_2_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_2_we1 <= grp_load_and_rearrange_q_fu_92_Q_2_we1;
        else 
            Q_2_we1 <= ap_const_logic_0;
        end if; 
    end process;


    Q_3_address0_assign_proc : process(grp_compute_attention_fu_56_Q_3_address0, grp_load_and_rearrange_q_fu_92_Q_3_address0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_3_address0 <= grp_load_and_rearrange_q_fu_92_Q_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_3_address0 <= grp_compute_attention_fu_56_Q_3_address0;
        else 
            Q_3_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    Q_3_address1_assign_proc : process(grp_compute_attention_fu_56_Q_3_address1, grp_load_and_rearrange_q_fu_92_Q_3_address1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_3_address1 <= grp_load_and_rearrange_q_fu_92_Q_3_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_3_address1 <= grp_compute_attention_fu_56_Q_3_address1;
        else 
            Q_3_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    Q_3_ce0_assign_proc : process(grp_compute_attention_fu_56_Q_3_ce0, grp_load_and_rearrange_q_fu_92_Q_3_ce0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_3_ce0 <= grp_load_and_rearrange_q_fu_92_Q_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_3_ce0 <= grp_compute_attention_fu_56_Q_3_ce0;
        else 
            Q_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    Q_3_ce1_assign_proc : process(grp_compute_attention_fu_56_Q_3_ce1, grp_load_and_rearrange_q_fu_92_Q_3_ce1, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_3_ce1 <= grp_load_and_rearrange_q_fu_92_Q_3_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            Q_3_ce1 <= grp_compute_attention_fu_56_Q_3_ce1;
        else 
            Q_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    Q_3_we0_assign_proc : process(grp_load_and_rearrange_q_fu_92_Q_3_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_3_we0 <= grp_load_and_rearrange_q_fu_92_Q_3_we0;
        else 
            Q_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    Q_3_we1_assign_proc : process(grp_load_and_rearrange_q_fu_92_Q_3_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            Q_3_we1 <= grp_load_and_rearrange_q_fu_92_Q_3_we1;
        else 
            Q_3_we1 <= ap_const_logic_0;
        end if; 
    end process;


    V_0_address0_assign_proc : process(grp_compute_attention_fu_56_V_0_address0, grp_load_and_rearrange_q_fu_92_V_0_address0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_0_address0 <= grp_load_and_rearrange_q_fu_92_V_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            V_0_address0 <= grp_compute_attention_fu_56_V_0_address0;
        else 
            V_0_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    V_0_ce0_assign_proc : process(grp_compute_attention_fu_56_V_0_ce0, grp_load_and_rearrange_q_fu_92_V_0_ce0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_0_ce0 <= grp_load_and_rearrange_q_fu_92_V_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            V_0_ce0 <= grp_compute_attention_fu_56_V_0_ce0;
        else 
            V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    V_0_ce1_assign_proc : process(grp_load_and_rearrange_q_fu_92_V_0_ce1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_0_ce1 <= grp_load_and_rearrange_q_fu_92_V_0_ce1;
        else 
            V_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    V_0_we0_assign_proc : process(grp_load_and_rearrange_q_fu_92_V_0_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_0_we0 <= grp_load_and_rearrange_q_fu_92_V_0_we0;
        else 
            V_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    V_0_we1_assign_proc : process(grp_load_and_rearrange_q_fu_92_V_0_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_0_we1 <= grp_load_and_rearrange_q_fu_92_V_0_we1;
        else 
            V_0_we1 <= ap_const_logic_0;
        end if; 
    end process;


    V_1_address0_assign_proc : process(grp_compute_attention_fu_56_V_1_address0, grp_load_and_rearrange_q_fu_92_V_1_address0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_1_address0 <= grp_load_and_rearrange_q_fu_92_V_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            V_1_address0 <= grp_compute_attention_fu_56_V_1_address0;
        else 
            V_1_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    V_1_ce0_assign_proc : process(grp_compute_attention_fu_56_V_1_ce0, grp_load_and_rearrange_q_fu_92_V_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_1_ce0 <= grp_load_and_rearrange_q_fu_92_V_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            V_1_ce0 <= grp_compute_attention_fu_56_V_1_ce0;
        else 
            V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    V_1_ce1_assign_proc : process(grp_load_and_rearrange_q_fu_92_V_1_ce1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_1_ce1 <= grp_load_and_rearrange_q_fu_92_V_1_ce1;
        else 
            V_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    V_1_we0_assign_proc : process(grp_load_and_rearrange_q_fu_92_V_1_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_1_we0 <= grp_load_and_rearrange_q_fu_92_V_1_we0;
        else 
            V_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    V_1_we1_assign_proc : process(grp_load_and_rearrange_q_fu_92_V_1_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_1_we1 <= grp_load_and_rearrange_q_fu_92_V_1_we1;
        else 
            V_1_we1 <= ap_const_logic_0;
        end if; 
    end process;


    V_2_address0_assign_proc : process(grp_compute_attention_fu_56_V_2_address0, grp_load_and_rearrange_q_fu_92_V_2_address0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_2_address0 <= grp_load_and_rearrange_q_fu_92_V_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            V_2_address0 <= grp_compute_attention_fu_56_V_2_address0;
        else 
            V_2_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    V_2_ce0_assign_proc : process(grp_compute_attention_fu_56_V_2_ce0, grp_load_and_rearrange_q_fu_92_V_2_ce0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_2_ce0 <= grp_load_and_rearrange_q_fu_92_V_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            V_2_ce0 <= grp_compute_attention_fu_56_V_2_ce0;
        else 
            V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    V_2_ce1_assign_proc : process(grp_load_and_rearrange_q_fu_92_V_2_ce1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_2_ce1 <= grp_load_and_rearrange_q_fu_92_V_2_ce1;
        else 
            V_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    V_2_we0_assign_proc : process(grp_load_and_rearrange_q_fu_92_V_2_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_2_we0 <= grp_load_and_rearrange_q_fu_92_V_2_we0;
        else 
            V_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    V_2_we1_assign_proc : process(grp_load_and_rearrange_q_fu_92_V_2_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_2_we1 <= grp_load_and_rearrange_q_fu_92_V_2_we1;
        else 
            V_2_we1 <= ap_const_logic_0;
        end if; 
    end process;


    V_3_address0_assign_proc : process(grp_compute_attention_fu_56_V_3_address0, grp_load_and_rearrange_q_fu_92_V_3_address0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_3_address0 <= grp_load_and_rearrange_q_fu_92_V_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            V_3_address0 <= grp_compute_attention_fu_56_V_3_address0;
        else 
            V_3_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    V_3_ce0_assign_proc : process(grp_compute_attention_fu_56_V_3_ce0, grp_load_and_rearrange_q_fu_92_V_3_ce0, ap_CS_fsm_state4, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_3_ce0 <= grp_load_and_rearrange_q_fu_92_V_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            V_3_ce0 <= grp_compute_attention_fu_56_V_3_ce0;
        else 
            V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    V_3_ce1_assign_proc : process(grp_load_and_rearrange_q_fu_92_V_3_ce1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_3_ce1 <= grp_load_and_rearrange_q_fu_92_V_3_ce1;
        else 
            V_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    V_3_we0_assign_proc : process(grp_load_and_rearrange_q_fu_92_V_3_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_3_we0 <= grp_load_and_rearrange_q_fu_92_V_3_we0;
        else 
            V_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    V_3_we1_assign_proc : process(grp_load_and_rearrange_q_fu_92_V_3_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            V_3_we1 <= grp_load_and_rearrange_q_fu_92_V_3_we1;
        else 
            V_3_we1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_done_assign_proc : process(grp_store_output_fu_122_ap_done, ap_CS_fsm_state6)
    begin
        if (((grp_store_output_fu_122_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_store_output_fu_122_ap_done, ap_CS_fsm_state6)
    begin
        if (((grp_store_output_fu_122_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_compute_attention_fu_56_ap_start <= grp_compute_attention_fu_56_ap_start_reg;
    grp_load_and_rearrange_q_fu_92_ap_start <= grp_load_and_rearrange_q_fu_92_ap_start_reg;
    grp_store_output_fu_122_ap_start <= grp_store_output_fu_122_ap_start_reg;
    input_data_address0 <= grp_load_and_rearrange_q_fu_92_input_data_address0;
    input_data_address1 <= grp_load_and_rearrange_q_fu_92_input_data_address1;
    input_data_ce0 <= grp_load_and_rearrange_q_fu_92_input_data_ce0;
    input_data_ce1 <= grp_load_and_rearrange_q_fu_92_input_data_ce1;
    output_data_address0 <= grp_store_output_fu_122_output_data_address0;
    output_data_address1 <= grp_store_output_fu_122_output_data_address1;
    output_data_ce0 <= grp_store_output_fu_122_output_data_ce0;
    output_data_ce1 <= grp_store_output_fu_122_output_data_ce1;
    output_data_d0 <= grp_store_output_fu_122_output_data_d0;
    output_data_d1 <= grp_store_output_fu_122_output_data_d1;
    output_data_we0 <= grp_store_output_fu_122_output_data_we0;
    output_data_we1 <= grp_store_output_fu_122_output_data_we1;
end behav;
